// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mov_sum,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xa7a12tcsg325-1q,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.411000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1325,HLS_SYN_LUT=2034,HLS_VERSION=2018_3}" *)

module mov_sum (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        window_width_V,
        absolute_value_V,
        datain_V_dout,
        datain_V_empty_n,
        datain_V_read,
        sumout_V,
        sumout_V_ap_vld
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] window_width_V;
input  [0:0] absolute_value_V;
input  [9:0] datain_V_dout;
input   datain_V_empty_n;
output   datain_V_read;
output  [31:0] sumout_V;
output   sumout_V_ap_vld;

reg ap_idle;
reg datain_V_read;
reg sumout_V_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    datain_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg   [9:0] datamem_127_V_reg_91;
reg   [9:0] datamem_126_V_reg_102;
reg   [9:0] datamem_125_V_reg_115;
reg   [9:0] datamem_124_V_reg_128;
reg   [9:0] datamem_123_V_reg_141;
reg   [9:0] datamem_122_V_reg_154;
reg   [9:0] datamem_121_V_reg_167;
reg   [9:0] datamem_120_V_reg_180;
reg   [9:0] datamem_119_V_reg_193;
reg   [9:0] datamem_118_V_reg_206;
reg   [9:0] datamem_117_V_reg_219;
reg   [9:0] datamem_116_V_reg_232;
reg   [9:0] datamem_115_V_reg_245;
reg   [9:0] datamem_114_V_reg_258;
reg   [9:0] datamem_113_V_reg_271;
reg   [9:0] datamem_112_V_reg_284;
reg   [9:0] datamem_111_V_reg_297;
reg   [9:0] datamem_110_V_reg_310;
reg   [9:0] datamem_109_V_reg_323;
reg   [9:0] datamem_108_V_reg_336;
reg   [9:0] datamem_107_V_reg_349;
reg   [9:0] datamem_106_V_reg_362;
reg   [9:0] datamem_105_V_reg_375;
reg   [9:0] datamem_104_V_reg_388;
reg   [9:0] datamem_103_V_reg_401;
reg   [9:0] datamem_102_V_reg_414;
reg   [9:0] datamem_101_V_reg_427;
reg   [9:0] datamem_100_V_reg_440;
reg   [9:0] datamem_99_V_reg_453;
reg   [9:0] datamem_98_V_reg_466;
reg   [9:0] datamem_97_V_reg_479;
reg   [9:0] datamem_96_V_reg_492;
reg   [9:0] datamem_95_V_reg_505;
reg   [9:0] datamem_94_V_reg_518;
reg   [9:0] datamem_93_V_reg_531;
reg   [9:0] datamem_92_V_reg_544;
reg   [9:0] datamem_91_V_reg_557;
reg   [9:0] datamem_90_V_reg_570;
reg   [9:0] datamem_89_V_reg_583;
reg   [9:0] datamem_88_V_reg_596;
reg   [9:0] datamem_87_V_reg_609;
reg   [9:0] datamem_86_V_reg_622;
reg   [9:0] datamem_85_V_reg_635;
reg   [9:0] datamem_84_V_reg_648;
reg   [9:0] datamem_83_V_reg_661;
reg   [9:0] datamem_82_V_reg_674;
reg   [9:0] datamem_81_V_reg_687;
reg   [9:0] datamem_80_V_reg_700;
reg   [9:0] datamem_79_V_reg_713;
reg   [9:0] datamem_78_V_reg_726;
reg   [9:0] datamem_77_V_reg_739;
reg   [9:0] datamem_76_V_reg_752;
reg   [9:0] datamem_75_V_reg_765;
reg   [9:0] datamem_74_V_reg_778;
reg   [9:0] datamem_73_V_reg_791;
reg   [9:0] datamem_72_V_reg_804;
reg   [9:0] datamem_71_V_reg_817;
reg   [9:0] datamem_70_V_reg_830;
reg   [9:0] datamem_69_V_reg_843;
reg   [9:0] datamem_68_V_reg_856;
reg   [9:0] datamem_67_V_reg_869;
reg   [9:0] datamem_66_V_reg_882;
reg   [9:0] datamem_65_V_reg_895;
reg   [9:0] datamem_64_V_reg_908;
reg   [9:0] datamem_63_V_reg_921;
reg   [9:0] datamem_62_V_reg_934;
reg   [9:0] datamem_61_V_reg_947;
reg   [9:0] datamem_60_V_reg_960;
reg   [9:0] datamem_59_V_reg_973;
reg   [9:0] datamem_58_V_reg_986;
reg   [9:0] datamem_57_V_reg_999;
reg   [9:0] datamem_56_V_reg_1012;
reg   [9:0] datamem_55_V_reg_1025;
reg   [9:0] datamem_54_V_reg_1038;
reg   [9:0] datamem_53_V_reg_1051;
reg   [9:0] datamem_52_V_reg_1064;
reg   [9:0] datamem_51_V_reg_1077;
reg   [9:0] datamem_50_V_reg_1090;
reg   [9:0] datamem_49_V_reg_1103;
reg   [9:0] datamem_48_V_reg_1116;
reg   [9:0] datamem_47_V_reg_1129;
reg   [9:0] datamem_46_V_reg_1142;
reg   [9:0] datamem_45_V_reg_1155;
reg   [9:0] datamem_44_V_reg_1168;
reg   [9:0] datamem_43_V_reg_1181;
reg   [9:0] datamem_42_V_reg_1194;
reg   [9:0] datamem_41_V_reg_1207;
reg   [9:0] datamem_40_V_reg_1220;
reg   [9:0] datamem_39_V_reg_1233;
reg   [9:0] datamem_38_V_reg_1246;
reg   [9:0] datamem_37_V_reg_1259;
reg   [9:0] datamem_36_V_reg_1272;
reg   [9:0] datamem_35_V_reg_1285;
reg   [9:0] datamem_34_V_reg_1298;
reg   [9:0] datamem_33_V_reg_1311;
reg   [9:0] datamem_32_V_reg_1324;
reg   [9:0] datamem_31_V_reg_1337;
reg   [9:0] datamem_30_V_reg_1350;
reg   [9:0] datamem_29_V_reg_1363;
reg   [9:0] datamem_28_V_reg_1376;
reg   [9:0] datamem_27_V_reg_1389;
reg   [9:0] datamem_26_V_reg_1402;
reg   [9:0] datamem_25_V_reg_1415;
reg   [9:0] datamem_24_V_reg_1428;
reg   [9:0] datamem_23_V_reg_1441;
reg   [9:0] datamem_22_V_reg_1454;
reg   [9:0] datamem_21_V_reg_1467;
reg   [9:0] datamem_20_V_reg_1480;
reg   [9:0] datamem_19_V_reg_1493;
reg   [9:0] datamem_18_V_reg_1506;
reg   [9:0] datamem_17_V_reg_1519;
reg   [9:0] datamem_16_V_reg_1532;
reg   [9:0] datamem_15_V_reg_1545;
reg   [9:0] datamem_14_V_reg_1558;
reg   [9:0] datamem_13_V_reg_1571;
reg   [9:0] datamem_12_V_reg_1584;
reg   [9:0] datamem_11_V_reg_1597;
reg   [9:0] datamem_10_V_reg_1610;
reg   [9:0] datamem_9_V_reg_1623;
reg   [9:0] datamem_8_V_reg_1636;
reg   [9:0] datamem_7_V_reg_1649;
reg   [9:0] datamem_6_V_reg_1662;
reg   [9:0] datamem_5_V_reg_1675;
reg   [9:0] datamem_4_V_reg_1688;
reg   [9:0] datamem_3_V_reg_1701;
reg   [9:0] datamem_2_V_reg_1714;
reg   [9:0] datamem_1_V_reg_1727;
reg   [31:0] p_s_reg_1740;
wire   [8:0] ret_V_fu_1759_p2;
wire   [9:0] tmp_V_2_fu_1798_p3;
reg   [9:0] tmp_V_2_reg_2128;
reg    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] tmp_7_fu_1810_p2;
reg   [0:0] tmp_7_reg_2135;
wire   [31:0] totalsum_V_fu_2099_p2;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_pp0_stage0_subdone;
reg   [7:0] shift_cnt_V_1_fu_62;
wire   [7:0] shift_cnt_V_fu_1815_p2;
reg    ap_block_pp0_stage0_01001;
wire   [8:0] lhs_V_cast_fu_1755_p1;
wire   [0:0] tmp_8_fu_1773_p3;
wire   [0:0] rev_fu_1781_p2;
wire   [0:0] or_cond_fu_1787_p2;
wire   [9:0] tmp_2_fu_1792_p2;
wire   [8:0] tmp_cast_fu_1806_p1;
wire   [6:0] tmp_4_fu_1829_p129;
wire   [9:0] tmp_4_fu_1829_p130;
wire   [31:0] tmp_3_fu_1826_p1;
wire   [31:0] tmp_6_fu_2093_p2;
wire   [31:0] tmp_5_fu_2089_p1;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

mov_sum_mux_1287_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 10 ),
    .din3_WIDTH( 10 ),
    .din4_WIDTH( 10 ),
    .din5_WIDTH( 10 ),
    .din6_WIDTH( 10 ),
    .din7_WIDTH( 10 ),
    .din8_WIDTH( 10 ),
    .din9_WIDTH( 10 ),
    .din10_WIDTH( 10 ),
    .din11_WIDTH( 10 ),
    .din12_WIDTH( 10 ),
    .din13_WIDTH( 10 ),
    .din14_WIDTH( 10 ),
    .din15_WIDTH( 10 ),
    .din16_WIDTH( 10 ),
    .din17_WIDTH( 10 ),
    .din18_WIDTH( 10 ),
    .din19_WIDTH( 10 ),
    .din20_WIDTH( 10 ),
    .din21_WIDTH( 10 ),
    .din22_WIDTH( 10 ),
    .din23_WIDTH( 10 ),
    .din24_WIDTH( 10 ),
    .din25_WIDTH( 10 ),
    .din26_WIDTH( 10 ),
    .din27_WIDTH( 10 ),
    .din28_WIDTH( 10 ),
    .din29_WIDTH( 10 ),
    .din30_WIDTH( 10 ),
    .din31_WIDTH( 10 ),
    .din32_WIDTH( 10 ),
    .din33_WIDTH( 10 ),
    .din34_WIDTH( 10 ),
    .din35_WIDTH( 10 ),
    .din36_WIDTH( 10 ),
    .din37_WIDTH( 10 ),
    .din38_WIDTH( 10 ),
    .din39_WIDTH( 10 ),
    .din40_WIDTH( 10 ),
    .din41_WIDTH( 10 ),
    .din42_WIDTH( 10 ),
    .din43_WIDTH( 10 ),
    .din44_WIDTH( 10 ),
    .din45_WIDTH( 10 ),
    .din46_WIDTH( 10 ),
    .din47_WIDTH( 10 ),
    .din48_WIDTH( 10 ),
    .din49_WIDTH( 10 ),
    .din50_WIDTH( 10 ),
    .din51_WIDTH( 10 ),
    .din52_WIDTH( 10 ),
    .din53_WIDTH( 10 ),
    .din54_WIDTH( 10 ),
    .din55_WIDTH( 10 ),
    .din56_WIDTH( 10 ),
    .din57_WIDTH( 10 ),
    .din58_WIDTH( 10 ),
    .din59_WIDTH( 10 ),
    .din60_WIDTH( 10 ),
    .din61_WIDTH( 10 ),
    .din62_WIDTH( 10 ),
    .din63_WIDTH( 10 ),
    .din64_WIDTH( 10 ),
    .din65_WIDTH( 10 ),
    .din66_WIDTH( 10 ),
    .din67_WIDTH( 10 ),
    .din68_WIDTH( 10 ),
    .din69_WIDTH( 10 ),
    .din70_WIDTH( 10 ),
    .din71_WIDTH( 10 ),
    .din72_WIDTH( 10 ),
    .din73_WIDTH( 10 ),
    .din74_WIDTH( 10 ),
    .din75_WIDTH( 10 ),
    .din76_WIDTH( 10 ),
    .din77_WIDTH( 10 ),
    .din78_WIDTH( 10 ),
    .din79_WIDTH( 10 ),
    .din80_WIDTH( 10 ),
    .din81_WIDTH( 10 ),
    .din82_WIDTH( 10 ),
    .din83_WIDTH( 10 ),
    .din84_WIDTH( 10 ),
    .din85_WIDTH( 10 ),
    .din86_WIDTH( 10 ),
    .din87_WIDTH( 10 ),
    .din88_WIDTH( 10 ),
    .din89_WIDTH( 10 ),
    .din90_WIDTH( 10 ),
    .din91_WIDTH( 10 ),
    .din92_WIDTH( 10 ),
    .din93_WIDTH( 10 ),
    .din94_WIDTH( 10 ),
    .din95_WIDTH( 10 ),
    .din96_WIDTH( 10 ),
    .din97_WIDTH( 10 ),
    .din98_WIDTH( 10 ),
    .din99_WIDTH( 10 ),
    .din100_WIDTH( 10 ),
    .din101_WIDTH( 10 ),
    .din102_WIDTH( 10 ),
    .din103_WIDTH( 10 ),
    .din104_WIDTH( 10 ),
    .din105_WIDTH( 10 ),
    .din106_WIDTH( 10 ),
    .din107_WIDTH( 10 ),
    .din108_WIDTH( 10 ),
    .din109_WIDTH( 10 ),
    .din110_WIDTH( 10 ),
    .din111_WIDTH( 10 ),
    .din112_WIDTH( 10 ),
    .din113_WIDTH( 10 ),
    .din114_WIDTH( 10 ),
    .din115_WIDTH( 10 ),
    .din116_WIDTH( 10 ),
    .din117_WIDTH( 10 ),
    .din118_WIDTH( 10 ),
    .din119_WIDTH( 10 ),
    .din120_WIDTH( 10 ),
    .din121_WIDTH( 10 ),
    .din122_WIDTH( 10 ),
    .din123_WIDTH( 10 ),
    .din124_WIDTH( 10 ),
    .din125_WIDTH( 10 ),
    .din126_WIDTH( 10 ),
    .din127_WIDTH( 10 ),
    .din128_WIDTH( 7 ),
    .dout_WIDTH( 10 ))
mov_sum_mux_1287_10_1_1_U1(
    .din0(tmp_V_2_reg_2128),
    .din1(datamem_1_V_reg_1727),
    .din2(datamem_2_V_reg_1714),
    .din3(datamem_3_V_reg_1701),
    .din4(datamem_4_V_reg_1688),
    .din5(datamem_5_V_reg_1675),
    .din6(datamem_6_V_reg_1662),
    .din7(datamem_7_V_reg_1649),
    .din8(datamem_8_V_reg_1636),
    .din9(datamem_9_V_reg_1623),
    .din10(datamem_10_V_reg_1610),
    .din11(datamem_11_V_reg_1597),
    .din12(datamem_12_V_reg_1584),
    .din13(datamem_13_V_reg_1571),
    .din14(datamem_14_V_reg_1558),
    .din15(datamem_15_V_reg_1545),
    .din16(datamem_16_V_reg_1532),
    .din17(datamem_17_V_reg_1519),
    .din18(datamem_18_V_reg_1506),
    .din19(datamem_19_V_reg_1493),
    .din20(datamem_20_V_reg_1480),
    .din21(datamem_21_V_reg_1467),
    .din22(datamem_22_V_reg_1454),
    .din23(datamem_23_V_reg_1441),
    .din24(datamem_24_V_reg_1428),
    .din25(datamem_25_V_reg_1415),
    .din26(datamem_26_V_reg_1402),
    .din27(datamem_27_V_reg_1389),
    .din28(datamem_28_V_reg_1376),
    .din29(datamem_29_V_reg_1363),
    .din30(datamem_30_V_reg_1350),
    .din31(datamem_31_V_reg_1337),
    .din32(datamem_32_V_reg_1324),
    .din33(datamem_33_V_reg_1311),
    .din34(datamem_34_V_reg_1298),
    .din35(datamem_35_V_reg_1285),
    .din36(datamem_36_V_reg_1272),
    .din37(datamem_37_V_reg_1259),
    .din38(datamem_38_V_reg_1246),
    .din39(datamem_39_V_reg_1233),
    .din40(datamem_40_V_reg_1220),
    .din41(datamem_41_V_reg_1207),
    .din42(datamem_42_V_reg_1194),
    .din43(datamem_43_V_reg_1181),
    .din44(datamem_44_V_reg_1168),
    .din45(datamem_45_V_reg_1155),
    .din46(datamem_46_V_reg_1142),
    .din47(datamem_47_V_reg_1129),
    .din48(datamem_48_V_reg_1116),
    .din49(datamem_49_V_reg_1103),
    .din50(datamem_50_V_reg_1090),
    .din51(datamem_51_V_reg_1077),
    .din52(datamem_52_V_reg_1064),
    .din53(datamem_53_V_reg_1051),
    .din54(datamem_54_V_reg_1038),
    .din55(datamem_55_V_reg_1025),
    .din56(datamem_56_V_reg_1012),
    .din57(datamem_57_V_reg_999),
    .din58(datamem_58_V_reg_986),
    .din59(datamem_59_V_reg_973),
    .din60(datamem_60_V_reg_960),
    .din61(datamem_61_V_reg_947),
    .din62(datamem_62_V_reg_934),
    .din63(datamem_63_V_reg_921),
    .din64(datamem_64_V_reg_908),
    .din65(datamem_65_V_reg_895),
    .din66(datamem_66_V_reg_882),
    .din67(datamem_67_V_reg_869),
    .din68(datamem_68_V_reg_856),
    .din69(datamem_69_V_reg_843),
    .din70(datamem_70_V_reg_830),
    .din71(datamem_71_V_reg_817),
    .din72(datamem_72_V_reg_804),
    .din73(datamem_73_V_reg_791),
    .din74(datamem_74_V_reg_778),
    .din75(datamem_75_V_reg_765),
    .din76(datamem_76_V_reg_752),
    .din77(datamem_77_V_reg_739),
    .din78(datamem_78_V_reg_726),
    .din79(datamem_79_V_reg_713),
    .din80(datamem_80_V_reg_700),
    .din81(datamem_81_V_reg_687),
    .din82(datamem_82_V_reg_674),
    .din83(datamem_83_V_reg_661),
    .din84(datamem_84_V_reg_648),
    .din85(datamem_85_V_reg_635),
    .din86(datamem_86_V_reg_622),
    .din87(datamem_87_V_reg_609),
    .din88(datamem_88_V_reg_596),
    .din89(datamem_89_V_reg_583),
    .din90(datamem_90_V_reg_570),
    .din91(datamem_91_V_reg_557),
    .din92(datamem_92_V_reg_544),
    .din93(datamem_93_V_reg_531),
    .din94(datamem_94_V_reg_518),
    .din95(datamem_95_V_reg_505),
    .din96(datamem_96_V_reg_492),
    .din97(datamem_97_V_reg_479),
    .din98(datamem_98_V_reg_466),
    .din99(datamem_99_V_reg_453),
    .din100(datamem_100_V_reg_440),
    .din101(datamem_101_V_reg_427),
    .din102(datamem_102_V_reg_414),
    .din103(datamem_103_V_reg_401),
    .din104(datamem_104_V_reg_388),
    .din105(datamem_105_V_reg_375),
    .din106(datamem_106_V_reg_362),
    .din107(datamem_107_V_reg_349),
    .din108(datamem_108_V_reg_336),
    .din109(datamem_109_V_reg_323),
    .din110(datamem_110_V_reg_310),
    .din111(datamem_111_V_reg_297),
    .din112(datamem_112_V_reg_284),
    .din113(datamem_113_V_reg_271),
    .din114(datamem_114_V_reg_258),
    .din115(datamem_115_V_reg_245),
    .din116(datamem_116_V_reg_232),
    .din117(datamem_117_V_reg_219),
    .din118(datamem_118_V_reg_206),
    .din119(datamem_119_V_reg_193),
    .din120(datamem_120_V_reg_180),
    .din121(datamem_121_V_reg_167),
    .din122(datamem_122_V_reg_154),
    .din123(datamem_123_V_reg_141),
    .din124(datamem_124_V_reg_128),
    .din125(datamem_125_V_reg_115),
    .din126(datamem_126_V_reg_102),
    .din127(datamem_127_V_reg_91),
    .din128(tmp_4_fu_1829_p129),
    .dout(tmp_4_fu_1829_p130)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_100_V_reg_440 <= datamem_99_V_reg_453;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_100_V_reg_440 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_101_V_reg_427 <= datamem_100_V_reg_440;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_101_V_reg_427 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_102_V_reg_414 <= datamem_101_V_reg_427;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_102_V_reg_414 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_103_V_reg_401 <= datamem_102_V_reg_414;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_103_V_reg_401 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_104_V_reg_388 <= datamem_103_V_reg_401;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_104_V_reg_388 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_105_V_reg_375 <= datamem_104_V_reg_388;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_105_V_reg_375 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_106_V_reg_362 <= datamem_105_V_reg_375;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_106_V_reg_362 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_107_V_reg_349 <= datamem_106_V_reg_362;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_107_V_reg_349 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_108_V_reg_336 <= datamem_107_V_reg_349;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_108_V_reg_336 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_109_V_reg_323 <= datamem_108_V_reg_336;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_109_V_reg_323 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_10_V_reg_1610 <= datamem_9_V_reg_1623;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_10_V_reg_1610 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_110_V_reg_310 <= datamem_109_V_reg_323;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_110_V_reg_310 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_111_V_reg_297 <= datamem_110_V_reg_310;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_111_V_reg_297 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_112_V_reg_284 <= datamem_111_V_reg_297;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_112_V_reg_284 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_113_V_reg_271 <= datamem_112_V_reg_284;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_113_V_reg_271 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_114_V_reg_258 <= datamem_113_V_reg_271;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_114_V_reg_258 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_115_V_reg_245 <= datamem_114_V_reg_258;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_115_V_reg_245 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_116_V_reg_232 <= datamem_115_V_reg_245;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_116_V_reg_232 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_117_V_reg_219 <= datamem_116_V_reg_232;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_117_V_reg_219 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_118_V_reg_206 <= datamem_117_V_reg_219;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_118_V_reg_206 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_119_V_reg_193 <= datamem_118_V_reg_206;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_119_V_reg_193 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_11_V_reg_1597 <= datamem_10_V_reg_1610;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_11_V_reg_1597 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_120_V_reg_180 <= datamem_119_V_reg_193;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_120_V_reg_180 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_121_V_reg_167 <= datamem_120_V_reg_180;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_121_V_reg_167 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_122_V_reg_154 <= datamem_121_V_reg_167;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_122_V_reg_154 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_123_V_reg_141 <= datamem_122_V_reg_154;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_123_V_reg_141 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_124_V_reg_128 <= datamem_123_V_reg_141;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_124_V_reg_128 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_125_V_reg_115 <= datamem_124_V_reg_128;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_125_V_reg_115 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_126_V_reg_102 <= datamem_125_V_reg_115;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_126_V_reg_102 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_127_V_reg_91 <= datamem_126_V_reg_102;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_127_V_reg_91 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_12_V_reg_1584 <= datamem_11_V_reg_1597;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_12_V_reg_1584 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_13_V_reg_1571 <= datamem_12_V_reg_1584;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_13_V_reg_1571 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_14_V_reg_1558 <= datamem_13_V_reg_1571;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_14_V_reg_1558 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_15_V_reg_1545 <= datamem_14_V_reg_1558;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_15_V_reg_1545 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_16_V_reg_1532 <= datamem_15_V_reg_1545;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_16_V_reg_1532 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_17_V_reg_1519 <= datamem_16_V_reg_1532;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_17_V_reg_1519 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_18_V_reg_1506 <= datamem_17_V_reg_1519;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_18_V_reg_1506 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_19_V_reg_1493 <= datamem_18_V_reg_1506;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_19_V_reg_1493 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_1_V_reg_1727 <= tmp_V_2_reg_2128;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_1_V_reg_1727 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_20_V_reg_1480 <= datamem_19_V_reg_1493;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_20_V_reg_1480 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_21_V_reg_1467 <= datamem_20_V_reg_1480;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_21_V_reg_1467 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_22_V_reg_1454 <= datamem_21_V_reg_1467;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_22_V_reg_1454 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_23_V_reg_1441 <= datamem_22_V_reg_1454;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_23_V_reg_1441 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_24_V_reg_1428 <= datamem_23_V_reg_1441;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_24_V_reg_1428 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_25_V_reg_1415 <= datamem_24_V_reg_1428;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_25_V_reg_1415 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_26_V_reg_1402 <= datamem_25_V_reg_1415;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_26_V_reg_1402 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_27_V_reg_1389 <= datamem_26_V_reg_1402;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_27_V_reg_1389 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_28_V_reg_1376 <= datamem_27_V_reg_1389;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_28_V_reg_1376 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_29_V_reg_1363 <= datamem_28_V_reg_1376;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_29_V_reg_1363 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_2_V_reg_1714 <= datamem_1_V_reg_1727;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_2_V_reg_1714 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_30_V_reg_1350 <= datamem_29_V_reg_1363;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_30_V_reg_1350 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_31_V_reg_1337 <= datamem_30_V_reg_1350;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_31_V_reg_1337 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_32_V_reg_1324 <= datamem_31_V_reg_1337;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_32_V_reg_1324 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_33_V_reg_1311 <= datamem_32_V_reg_1324;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_33_V_reg_1311 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_34_V_reg_1298 <= datamem_33_V_reg_1311;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_34_V_reg_1298 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_35_V_reg_1285 <= datamem_34_V_reg_1298;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_35_V_reg_1285 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_36_V_reg_1272 <= datamem_35_V_reg_1285;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_36_V_reg_1272 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_37_V_reg_1259 <= datamem_36_V_reg_1272;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_37_V_reg_1259 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_38_V_reg_1246 <= datamem_37_V_reg_1259;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_38_V_reg_1246 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_39_V_reg_1233 <= datamem_38_V_reg_1246;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_39_V_reg_1233 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_3_V_reg_1701 <= datamem_2_V_reg_1714;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_3_V_reg_1701 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_40_V_reg_1220 <= datamem_39_V_reg_1233;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_40_V_reg_1220 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_41_V_reg_1207 <= datamem_40_V_reg_1220;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_41_V_reg_1207 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_42_V_reg_1194 <= datamem_41_V_reg_1207;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_42_V_reg_1194 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_43_V_reg_1181 <= datamem_42_V_reg_1194;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_43_V_reg_1181 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_44_V_reg_1168 <= datamem_43_V_reg_1181;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_44_V_reg_1168 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_45_V_reg_1155 <= datamem_44_V_reg_1168;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_45_V_reg_1155 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_46_V_reg_1142 <= datamem_45_V_reg_1155;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_46_V_reg_1142 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_47_V_reg_1129 <= datamem_46_V_reg_1142;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_47_V_reg_1129 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_48_V_reg_1116 <= datamem_47_V_reg_1129;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_48_V_reg_1116 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_49_V_reg_1103 <= datamem_48_V_reg_1116;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_49_V_reg_1103 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_4_V_reg_1688 <= datamem_3_V_reg_1701;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_4_V_reg_1688 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_50_V_reg_1090 <= datamem_49_V_reg_1103;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_50_V_reg_1090 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_51_V_reg_1077 <= datamem_50_V_reg_1090;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_51_V_reg_1077 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_52_V_reg_1064 <= datamem_51_V_reg_1077;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_52_V_reg_1064 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_53_V_reg_1051 <= datamem_52_V_reg_1064;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_53_V_reg_1051 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_54_V_reg_1038 <= datamem_53_V_reg_1051;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_54_V_reg_1038 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_55_V_reg_1025 <= datamem_54_V_reg_1038;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_55_V_reg_1025 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_56_V_reg_1012 <= datamem_55_V_reg_1025;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_56_V_reg_1012 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_57_V_reg_999 <= datamem_56_V_reg_1012;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_57_V_reg_999 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_58_V_reg_986 <= datamem_57_V_reg_999;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_58_V_reg_986 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_59_V_reg_973 <= datamem_58_V_reg_986;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_59_V_reg_973 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_5_V_reg_1675 <= datamem_4_V_reg_1688;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_5_V_reg_1675 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_60_V_reg_960 <= datamem_59_V_reg_973;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_60_V_reg_960 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_61_V_reg_947 <= datamem_60_V_reg_960;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_61_V_reg_947 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_62_V_reg_934 <= datamem_61_V_reg_947;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_62_V_reg_934 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_63_V_reg_921 <= datamem_62_V_reg_934;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_63_V_reg_921 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_64_V_reg_908 <= datamem_63_V_reg_921;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_64_V_reg_908 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_65_V_reg_895 <= datamem_64_V_reg_908;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_65_V_reg_895 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_66_V_reg_882 <= datamem_65_V_reg_895;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_66_V_reg_882 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_67_V_reg_869 <= datamem_66_V_reg_882;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_67_V_reg_869 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_68_V_reg_856 <= datamem_67_V_reg_869;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_68_V_reg_856 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_69_V_reg_843 <= datamem_68_V_reg_856;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_69_V_reg_843 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_6_V_reg_1662 <= datamem_5_V_reg_1675;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_6_V_reg_1662 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_70_V_reg_830 <= datamem_69_V_reg_843;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_70_V_reg_830 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_71_V_reg_817 <= datamem_70_V_reg_830;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_71_V_reg_817 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_72_V_reg_804 <= datamem_71_V_reg_817;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_72_V_reg_804 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_73_V_reg_791 <= datamem_72_V_reg_804;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_73_V_reg_791 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_74_V_reg_778 <= datamem_73_V_reg_791;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_74_V_reg_778 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_75_V_reg_765 <= datamem_74_V_reg_778;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_75_V_reg_765 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_76_V_reg_752 <= datamem_75_V_reg_765;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_76_V_reg_752 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_77_V_reg_739 <= datamem_76_V_reg_752;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_77_V_reg_739 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_78_V_reg_726 <= datamem_77_V_reg_739;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_78_V_reg_726 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_79_V_reg_713 <= datamem_78_V_reg_726;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_79_V_reg_713 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_7_V_reg_1649 <= datamem_6_V_reg_1662;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_7_V_reg_1649 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_80_V_reg_700 <= datamem_79_V_reg_713;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_80_V_reg_700 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_81_V_reg_687 <= datamem_80_V_reg_700;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_81_V_reg_687 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_82_V_reg_674 <= datamem_81_V_reg_687;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_82_V_reg_674 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_83_V_reg_661 <= datamem_82_V_reg_674;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_83_V_reg_661 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_84_V_reg_648 <= datamem_83_V_reg_661;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_84_V_reg_648 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_85_V_reg_635 <= datamem_84_V_reg_648;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_85_V_reg_635 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_86_V_reg_622 <= datamem_85_V_reg_635;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_86_V_reg_622 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_87_V_reg_609 <= datamem_86_V_reg_622;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_87_V_reg_609 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_88_V_reg_596 <= datamem_87_V_reg_609;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_88_V_reg_596 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_89_V_reg_583 <= datamem_88_V_reg_596;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_89_V_reg_583 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_8_V_reg_1636 <= datamem_7_V_reg_1649;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_8_V_reg_1636 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_90_V_reg_570 <= datamem_89_V_reg_583;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_90_V_reg_570 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_91_V_reg_557 <= datamem_90_V_reg_570;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_91_V_reg_557 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_92_V_reg_544 <= datamem_91_V_reg_557;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_92_V_reg_544 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_93_V_reg_531 <= datamem_92_V_reg_544;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_93_V_reg_531 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_94_V_reg_518 <= datamem_93_V_reg_531;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_94_V_reg_518 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_95_V_reg_505 <= datamem_94_V_reg_518;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_95_V_reg_505 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_96_V_reg_492 <= datamem_95_V_reg_505;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_96_V_reg_492 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_97_V_reg_479 <= datamem_96_V_reg_492;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_97_V_reg_479 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_98_V_reg_466 <= datamem_97_V_reg_479;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_98_V_reg_466 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_99_V_reg_453 <= datamem_98_V_reg_466;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_99_V_reg_453 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        datamem_9_V_reg_1623 <= datamem_8_V_reg_1636;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        datamem_9_V_reg_1623 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        p_s_reg_1740 <= totalsum_V_fu_2099_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_s_reg_1740 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_7_fu_1810_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shift_cnt_V_1_fu_62 <= shift_cnt_V_fu_1815_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        shift_cnt_V_1_fu_62 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_7_reg_2135 <= tmp_7_fu_1810_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_V_2_reg_2128 <= tmp_V_2_fu_1798_p3;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        datain_V_blk_n = datain_V_empty_n;
    end else begin
        datain_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        datain_V_read = 1'b1;
    end else begin
        datain_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_7_reg_2135 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        sumout_V_ap_vld = 1'b1;
    end else begin
        sumout_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((datain_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((datain_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((datain_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = (datain_V_empty_n == 1'b0);
end

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_done = 1'b0;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = 1'b0;

assign lhs_V_cast_fu_1755_p1 = window_width_V;

assign or_cond_fu_1787_p2 = (rev_fu_1781_p2 & absolute_value_V);

assign ret_V_fu_1759_p2 = ($signed(9'd511) + $signed(lhs_V_cast_fu_1755_p1));

assign rev_fu_1781_p2 = (tmp_8_fu_1773_p3 ^ 1'd1);

assign shift_cnt_V_fu_1815_p2 = (shift_cnt_V_1_fu_62 + 8'd1);

assign sumout_V = (tmp_6_fu_2093_p2 - tmp_5_fu_2089_p1);

assign tmp_2_fu_1792_p2 = (datain_V_dout ^ 10'd1023);

assign tmp_3_fu_1826_p1 = tmp_V_2_reg_2128;

assign tmp_4_fu_1829_p129 = window_width_V[6:0];

assign tmp_5_fu_2089_p1 = tmp_4_fu_1829_p130;

assign tmp_6_fu_2093_p2 = (p_s_reg_1740 + tmp_3_fu_1826_p1);

assign tmp_7_fu_1810_p2 = (($signed(tmp_cast_fu_1806_p1) < $signed(ret_V_fu_1759_p2)) ? 1'b1 : 1'b0);

assign tmp_8_fu_1773_p3 = datain_V_dout[32'd9];

assign tmp_V_2_fu_1798_p3 = ((or_cond_fu_1787_p2[0:0] === 1'b1) ? tmp_2_fu_1792_p2 : datain_V_dout);

assign tmp_cast_fu_1806_p1 = shift_cnt_V_1_fu_62;

assign totalsum_V_fu_2099_p2 = (tmp_6_fu_2093_p2 - tmp_5_fu_2089_p1);

endmodule //mov_sum
