// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="sad,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcku035-sfva784-2-i,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=14.010750,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1288,HLS_SYN_LUT=4932,HLS_VERSION=2018_3}" *)

module sad (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        max_points_V,
        ref_points_in_V_dout,
        ref_points_in_V_empty_n,
        ref_points_in_V_read,
        datain_V_dout,
        datain_V_empty_n,
        datain_V_read,
        sumout_V_din,
        sumout_V_full_n,
        sumout_V_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [6:0] max_points_V;
input  [9:0] ref_points_in_V_dout;
input   ref_points_in_V_empty_n;
output   ref_points_in_V_read;
input  [9:0] datain_V_dout;
input   datain_V_empty_n;
output   datain_V_read;
output  [19:0] sumout_V_din;
input   sumout_V_full_n;
output   sumout_V_write;

reg ap_idle;
reg ref_points_in_V_read;
reg datain_V_read;
reg sumout_V_write;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ref_points_in_V_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] exitcond1_fu_716_p2;
reg    datain_V_blk_n;
wire    ap_CS_fsm_state4;
reg    sumout_V_blk_n;
wire   [6:0] i_1_fu_722_p2;
reg   [6:0] i_1_reg_4686;
reg    ap_block_state2;
reg   [6:0] i_reg_705;
wire    ap_CS_fsm_state3;
reg    ap_block_state4;
reg   [9:0] ref_points_63_V_fu_178;
wire   [5:0] tmp_3_fu_728_p1;
reg   [9:0] ref_points_63_V_1_fu_182;
reg   [9:0] ref_points_63_V_2_fu_186;
reg   [9:0] ref_points_63_V_3_fu_190;
reg   [9:0] ref_points_63_V_4_fu_194;
reg   [9:0] ref_points_63_V_5_fu_198;
reg   [9:0] ref_points_63_V_6_fu_202;
reg   [9:0] ref_points_63_V_7_fu_206;
reg   [9:0] ref_points_63_V_8_fu_210;
reg   [9:0] ref_points_63_V_9_fu_214;
reg   [9:0] ref_points_63_V_10_fu_218;
reg   [9:0] ref_points_63_V_11_fu_222;
reg   [9:0] ref_points_63_V_12_fu_226;
reg   [9:0] ref_points_63_V_13_fu_230;
reg   [9:0] ref_points_63_V_14_fu_234;
reg   [9:0] ref_points_63_V_15_fu_238;
reg   [9:0] ref_points_63_V_16_fu_242;
reg   [9:0] ref_points_63_V_17_fu_246;
reg   [9:0] ref_points_63_V_18_fu_250;
reg   [9:0] ref_points_63_V_19_fu_254;
reg   [9:0] ref_points_63_V_20_fu_258;
reg   [9:0] ref_points_63_V_21_fu_262;
reg   [9:0] ref_points_63_V_22_fu_266;
reg   [9:0] ref_points_63_V_23_fu_270;
reg   [9:0] ref_points_63_V_24_fu_274;
reg   [9:0] ref_points_63_V_25_fu_278;
reg   [9:0] ref_points_63_V_26_fu_282;
reg   [9:0] ref_points_63_V_27_fu_286;
reg   [9:0] ref_points_63_V_28_fu_290;
reg   [9:0] ref_points_63_V_29_fu_294;
reg   [9:0] ref_points_63_V_30_fu_298;
reg   [9:0] ref_points_63_V_31_fu_302;
reg   [9:0] ref_points_63_V_32_fu_306;
reg   [9:0] ref_points_63_V_33_fu_310;
reg   [9:0] ref_points_63_V_34_fu_314;
reg   [9:0] ref_points_63_V_35_fu_318;
reg   [9:0] ref_points_63_V_36_fu_322;
reg   [9:0] ref_points_63_V_37_fu_326;
reg   [9:0] ref_points_63_V_38_fu_330;
reg   [9:0] ref_points_63_V_39_fu_334;
reg   [9:0] ref_points_63_V_40_fu_338;
reg   [9:0] ref_points_63_V_41_fu_342;
reg   [9:0] ref_points_63_V_42_fu_346;
reg   [9:0] ref_points_63_V_43_fu_350;
reg   [9:0] ref_points_63_V_44_fu_354;
reg   [9:0] ref_points_63_V_45_fu_358;
reg   [9:0] ref_points_63_V_46_fu_362;
reg   [9:0] ref_points_63_V_47_fu_366;
reg   [9:0] ref_points_63_V_48_fu_370;
reg   [9:0] ref_points_63_V_49_fu_374;
reg   [9:0] ref_points_63_V_50_fu_378;
reg   [9:0] ref_points_63_V_51_fu_382;
reg   [9:0] ref_points_63_V_52_fu_386;
reg   [9:0] ref_points_63_V_53_fu_390;
reg   [9:0] ref_points_63_V_54_fu_394;
reg   [9:0] ref_points_63_V_55_fu_398;
reg   [9:0] ref_points_63_V_56_fu_402;
reg   [9:0] ref_points_63_V_57_fu_406;
reg   [9:0] ref_points_63_V_58_fu_410;
reg   [9:0] ref_points_63_V_59_fu_414;
reg   [9:0] ref_points_63_V_60_fu_418;
reg   [9:0] ref_points_63_V_61_fu_422;
reg   [9:0] ref_points_63_V_62_fu_426;
reg   [9:0] ref_points_63_V_63_fu_430;
reg   [9:0] datamem_1_V_fu_434;
reg   [9:0] datamem_2_V_fu_438;
reg   [9:0] datamem_3_V_fu_442;
reg   [9:0] datamem_4_V_fu_446;
reg   [9:0] datamem_5_V_fu_450;
reg   [9:0] datamem_6_V_fu_454;
reg   [9:0] datamem_7_V_fu_458;
reg   [9:0] datamem_8_V_fu_462;
reg   [9:0] datamem_9_V_fu_466;
reg   [9:0] datamem_10_V_fu_470;
reg   [9:0] datamem_11_V_fu_474;
reg   [9:0] datamem_12_V_fu_478;
reg   [9:0] datamem_13_V_fu_482;
reg   [9:0] datamem_14_V_fu_486;
reg   [9:0] datamem_15_V_fu_490;
reg   [9:0] datamem_16_V_fu_494;
reg   [9:0] datamem_17_V_fu_498;
reg   [9:0] datamem_18_V_fu_502;
reg   [9:0] datamem_19_V_fu_506;
reg   [9:0] datamem_20_V_fu_510;
reg   [9:0] datamem_21_V_fu_514;
reg   [9:0] datamem_22_V_fu_518;
reg   [9:0] datamem_23_V_fu_522;
reg   [9:0] datamem_24_V_fu_526;
reg   [9:0] datamem_25_V_fu_530;
reg   [9:0] datamem_26_V_fu_534;
reg   [9:0] datamem_27_V_fu_538;
reg   [9:0] datamem_28_V_fu_542;
reg   [9:0] datamem_29_V_fu_546;
reg   [9:0] datamem_30_V_fu_550;
reg   [9:0] datamem_31_V_fu_554;
reg   [9:0] datamem_32_V_fu_558;
reg   [9:0] datamem_33_V_fu_562;
reg   [9:0] datamem_34_V_fu_566;
reg   [9:0] datamem_35_V_fu_570;
reg   [9:0] datamem_36_V_fu_574;
reg   [9:0] datamem_37_V_fu_578;
reg   [9:0] datamem_38_V_fu_582;
reg   [9:0] datamem_39_V_fu_586;
reg   [9:0] datamem_40_V_fu_590;
reg   [9:0] datamem_41_V_fu_594;
reg   [9:0] datamem_42_V_fu_598;
reg   [9:0] datamem_43_V_fu_602;
reg   [9:0] datamem_44_V_fu_606;
reg   [9:0] datamem_45_V_fu_610;
reg   [9:0] datamem_46_V_fu_614;
reg   [9:0] datamem_47_V_fu_618;
reg   [9:0] datamem_48_V_fu_622;
reg   [9:0] datamem_49_V_fu_626;
reg   [9:0] datamem_50_V_fu_630;
reg   [9:0] datamem_51_V_fu_634;
reg   [9:0] datamem_52_V_fu_638;
reg   [9:0] datamem_53_V_fu_642;
reg   [9:0] datamem_54_V_fu_646;
reg   [9:0] datamem_55_V_fu_650;
reg   [9:0] datamem_56_V_fu_654;
reg   [9:0] datamem_57_V_fu_658;
reg   [9:0] datamem_58_V_fu_662;
reg   [9:0] datamem_59_V_fu_666;
reg   [9:0] datamem_60_V_fu_670;
reg   [9:0] datamem_61_V_fu_674;
reg   [9:0] datamem_62_V_fu_678;
reg   [9:0] datamem_62_V_1_fu_682;
wire   [0:0] tmp_9_fu_1433_p2;
wire   [9:0] tmp_s_fu_1439_p2;
wire   [9:0] tmp_2_fu_1445_p2;
wire   [0:0] tmp_9_1_fu_1459_p2;
wire   [9:0] tmp_1_4_fu_1465_p2;
wire   [9:0] tmp_1_1_fu_1471_p2;
wire   [0:0] tmp_9_2_fu_1485_p2;
wire   [9:0] tmp_2_5_fu_1491_p2;
wire   [9:0] tmp_1_2_fu_1497_p2;
wire   [0:0] tmp_9_3_fu_1511_p2;
wire   [9:0] tmp_3_6_fu_1517_p2;
wire   [9:0] tmp_1_3_fu_1523_p2;
wire   [0:0] tmp_9_4_fu_1537_p2;
wire   [9:0] tmp_4_fu_1543_p2;
wire   [9:0] tmp_1_4_7_fu_1549_p2;
wire   [0:0] tmp_9_5_fu_1563_p2;
wire   [9:0] tmp_5_fu_1569_p2;
wire   [9:0] tmp_1_5_fu_1575_p2;
wire   [0:0] tmp_9_6_fu_1589_p2;
wire   [9:0] tmp_6_fu_1595_p2;
wire   [9:0] tmp_1_6_fu_1601_p2;
wire   [0:0] tmp_9_7_fu_1615_p2;
wire   [9:0] tmp_7_fu_1621_p2;
wire   [9:0] tmp_1_7_fu_1627_p2;
wire   [0:0] tmp_9_8_fu_1641_p2;
wire   [9:0] tmp_8_fu_1647_p2;
wire   [9:0] tmp_1_8_fu_1653_p2;
wire   [0:0] tmp_9_9_fu_1667_p2;
wire   [9:0] tmp_9_10_fu_1673_p2;
wire   [9:0] tmp_1_9_fu_1679_p2;
wire   [0:0] tmp_9_s_fu_1693_p2;
wire   [9:0] tmp_s_11_fu_1699_p2;
wire   [9:0] tmp_1_s_fu_1705_p2;
wire   [0:0] tmp_9_10_12_fu_1719_p2;
wire   [9:0] tmp_10_fu_1725_p2;
wire   [9:0] tmp_1_10_fu_1731_p2;
wire   [0:0] tmp_9_11_fu_1745_p2;
wire   [9:0] tmp_11_fu_1751_p2;
wire   [9:0] tmp_1_11_fu_1757_p2;
wire   [0:0] tmp_9_12_fu_1771_p2;
wire   [9:0] tmp_12_fu_1777_p2;
wire   [9:0] tmp_1_12_fu_1783_p2;
wire   [0:0] tmp_9_13_fu_1797_p2;
wire   [9:0] tmp_13_fu_1803_p2;
wire   [9:0] tmp_1_13_fu_1809_p2;
wire   [0:0] tmp_9_14_fu_1823_p2;
wire   [9:0] tmp_14_fu_1829_p2;
wire   [9:0] tmp_1_14_fu_1835_p2;
wire   [0:0] tmp_9_15_fu_1849_p2;
wire   [9:0] tmp_15_fu_1855_p2;
wire   [9:0] tmp_1_15_fu_1861_p2;
wire   [0:0] tmp_9_16_fu_1875_p2;
wire   [9:0] tmp_16_fu_1881_p2;
wire   [9:0] tmp_1_16_fu_1887_p2;
wire   [0:0] tmp_9_17_fu_1901_p2;
wire   [9:0] tmp_17_fu_1907_p2;
wire   [9:0] tmp_1_17_fu_1913_p2;
wire   [0:0] tmp_9_18_fu_1927_p2;
wire   [9:0] tmp_18_fu_1933_p2;
wire   [9:0] tmp_1_18_fu_1939_p2;
wire   [0:0] tmp_9_19_fu_1953_p2;
wire   [9:0] tmp_19_fu_1959_p2;
wire   [9:0] tmp_1_19_fu_1965_p2;
wire   [0:0] tmp_9_20_fu_1979_p2;
wire   [9:0] tmp_20_fu_1985_p2;
wire   [9:0] tmp_1_20_fu_1991_p2;
wire   [0:0] tmp_9_21_fu_2005_p2;
wire   [9:0] tmp_21_fu_2011_p2;
wire   [9:0] tmp_1_21_fu_2017_p2;
wire   [0:0] tmp_9_22_fu_2031_p2;
wire   [9:0] tmp_22_fu_2037_p2;
wire   [9:0] tmp_1_22_fu_2043_p2;
wire   [0:0] tmp_9_23_fu_2057_p2;
wire   [9:0] tmp_23_fu_2063_p2;
wire   [9:0] tmp_1_23_fu_2069_p2;
wire   [0:0] tmp_9_24_fu_2083_p2;
wire   [9:0] tmp_24_fu_2089_p2;
wire   [9:0] tmp_1_24_fu_2095_p2;
wire   [0:0] tmp_9_25_fu_2109_p2;
wire   [9:0] tmp_25_fu_2115_p2;
wire   [9:0] tmp_1_25_fu_2121_p2;
wire   [0:0] tmp_9_26_fu_2135_p2;
wire   [9:0] tmp_26_fu_2141_p2;
wire   [9:0] tmp_1_26_fu_2147_p2;
wire   [0:0] tmp_9_27_fu_2161_p2;
wire   [9:0] tmp_27_fu_2167_p2;
wire   [9:0] tmp_1_27_fu_2173_p2;
wire   [0:0] tmp_9_28_fu_2187_p2;
wire   [9:0] tmp_28_fu_2193_p2;
wire   [9:0] tmp_1_28_fu_2199_p2;
wire   [0:0] tmp_9_29_fu_2213_p2;
wire   [9:0] tmp_29_fu_2219_p2;
wire   [9:0] tmp_1_29_fu_2225_p2;
wire   [0:0] tmp_9_30_fu_2239_p2;
wire   [9:0] tmp_30_fu_2245_p2;
wire   [9:0] tmp_1_30_fu_2251_p2;
wire   [0:0] tmp_9_31_fu_2265_p2;
wire   [9:0] tmp_31_fu_2271_p2;
wire   [9:0] tmp_1_31_fu_2277_p2;
wire   [0:0] tmp_9_32_fu_2291_p2;
wire   [9:0] tmp_32_fu_2297_p2;
wire   [9:0] tmp_1_32_fu_2303_p2;
wire   [0:0] tmp_9_33_fu_2317_p2;
wire   [9:0] tmp_33_fu_2323_p2;
wire   [9:0] tmp_1_33_fu_2329_p2;
wire   [0:0] tmp_9_34_fu_2343_p2;
wire   [9:0] tmp_34_fu_2349_p2;
wire   [9:0] tmp_1_34_fu_2355_p2;
wire   [0:0] tmp_9_35_fu_2369_p2;
wire   [9:0] tmp_35_fu_2375_p2;
wire   [9:0] tmp_1_35_fu_2381_p2;
wire   [0:0] tmp_9_36_fu_2395_p2;
wire   [9:0] tmp_36_fu_2401_p2;
wire   [9:0] tmp_1_36_fu_2407_p2;
wire   [0:0] tmp_9_37_fu_2421_p2;
wire   [9:0] tmp_37_fu_2427_p2;
wire   [9:0] tmp_1_37_fu_2433_p2;
wire   [0:0] tmp_9_38_fu_2447_p2;
wire   [9:0] tmp_38_fu_2453_p2;
wire   [9:0] tmp_1_38_fu_2459_p2;
wire   [0:0] tmp_9_39_fu_2473_p2;
wire   [9:0] tmp_39_fu_2479_p2;
wire   [9:0] tmp_1_39_fu_2485_p2;
wire   [0:0] tmp_9_40_fu_2499_p2;
wire   [9:0] tmp_40_fu_2505_p2;
wire   [9:0] tmp_1_40_fu_2511_p2;
wire   [0:0] tmp_9_41_fu_2525_p2;
wire   [9:0] tmp_41_fu_2531_p2;
wire   [9:0] tmp_1_41_fu_2537_p2;
wire   [0:0] tmp_9_42_fu_2551_p2;
wire   [9:0] tmp_42_fu_2557_p2;
wire   [9:0] tmp_1_42_fu_2563_p2;
wire   [0:0] tmp_9_43_fu_2577_p2;
wire   [9:0] tmp_43_fu_2583_p2;
wire   [9:0] tmp_1_43_fu_2589_p2;
wire   [0:0] tmp_9_44_fu_2603_p2;
wire   [9:0] tmp_44_fu_2609_p2;
wire   [9:0] tmp_1_44_fu_2615_p2;
wire   [0:0] tmp_9_45_fu_2629_p2;
wire   [9:0] tmp_45_fu_2635_p2;
wire   [9:0] tmp_1_45_fu_2641_p2;
wire   [0:0] tmp_9_46_fu_2655_p2;
wire   [9:0] tmp_46_fu_2661_p2;
wire   [9:0] tmp_1_46_fu_2667_p2;
wire   [0:0] tmp_9_47_fu_2681_p2;
wire   [9:0] tmp_47_fu_2687_p2;
wire   [9:0] tmp_1_47_fu_2693_p2;
wire   [0:0] tmp_9_48_fu_2707_p2;
wire   [9:0] tmp_48_fu_2713_p2;
wire   [9:0] tmp_1_48_fu_2719_p2;
wire   [0:0] tmp_9_49_fu_2733_p2;
wire   [9:0] tmp_49_fu_2739_p2;
wire   [9:0] tmp_1_49_fu_2745_p2;
wire   [0:0] tmp_9_50_fu_2759_p2;
wire   [9:0] tmp_50_fu_2765_p2;
wire   [9:0] tmp_1_50_fu_2771_p2;
wire   [0:0] tmp_9_51_fu_2785_p2;
wire   [9:0] tmp_51_fu_2791_p2;
wire   [9:0] tmp_1_51_fu_2797_p2;
wire   [0:0] tmp_9_52_fu_2811_p2;
wire   [9:0] tmp_52_fu_2817_p2;
wire   [9:0] tmp_1_52_fu_2823_p2;
wire   [0:0] tmp_9_53_fu_2837_p2;
wire   [9:0] tmp_53_fu_2843_p2;
wire   [9:0] tmp_1_53_fu_2849_p2;
wire   [0:0] tmp_9_54_fu_2863_p2;
wire   [9:0] tmp_54_fu_2869_p2;
wire   [9:0] tmp_1_54_fu_2875_p2;
wire   [0:0] tmp_9_55_fu_2889_p2;
wire   [9:0] tmp_55_fu_2895_p2;
wire   [9:0] tmp_1_55_fu_2901_p2;
wire   [0:0] tmp_9_56_fu_2915_p2;
wire   [9:0] tmp_56_fu_2921_p2;
wire   [9:0] tmp_1_56_fu_2927_p2;
wire   [0:0] tmp_9_57_fu_2941_p2;
wire   [9:0] tmp_57_fu_2947_p2;
wire   [9:0] tmp_1_57_fu_2953_p2;
wire   [0:0] tmp_9_58_fu_2967_p2;
wire   [9:0] tmp_58_fu_2973_p2;
wire   [9:0] tmp_1_58_fu_2979_p2;
wire   [0:0] tmp_9_59_fu_2993_p2;
wire   [9:0] tmp_59_fu_2999_p2;
wire   [9:0] tmp_1_59_fu_3005_p2;
wire   [0:0] tmp_9_60_fu_3019_p2;
wire   [9:0] tmp_60_fu_3025_p2;
wire   [9:0] tmp_1_60_fu_3031_p2;
wire   [0:0] tmp_9_61_fu_3045_p2;
wire   [9:0] tmp_61_fu_3051_p2;
wire   [9:0] tmp_1_61_fu_3057_p2;
wire   [0:0] tmp_9_62_fu_3071_p2;
wire   [9:0] tmp_62_fu_3077_p2;
wire   [9:0] tmp_1_62_fu_3083_p2;
wire   [9:0] sumtree_0_V_fu_1451_p3;
wire   [9:0] sumtree_1_V_fu_1477_p3;
wire   [9:0] sumtree_2_V_fu_1503_p3;
wire   [9:0] sumtree_3_V_fu_1529_p3;
wire   [9:0] sumtree_4_V_fu_1555_p3;
wire   [9:0] sumtree_5_V_fu_1581_p3;
wire   [9:0] sumtree_6_V_fu_1607_p3;
wire   [9:0] sumtree_7_V_fu_1633_p3;
wire   [9:0] sumtree_8_V_fu_1659_p3;
wire   [9:0] sumtree_9_V_fu_1685_p3;
wire   [9:0] sumtree_10_V_fu_1711_p3;
wire   [9:0] sumtree_11_V_fu_1737_p3;
wire   [9:0] sumtree_12_V_fu_1763_p3;
wire   [9:0] sumtree_13_V_fu_1789_p3;
wire   [9:0] sumtree_14_V_fu_1815_p3;
wire   [9:0] sumtree_15_V_fu_1841_p3;
wire   [9:0] sumtree_16_V_fu_1867_p3;
wire   [9:0] sumtree_17_V_fu_1893_p3;
wire   [9:0] sumtree_18_V_fu_1919_p3;
wire   [9:0] sumtree_19_V_fu_1945_p3;
wire   [9:0] sumtree_20_V_fu_1971_p3;
wire   [9:0] sumtree_21_V_fu_1997_p3;
wire   [9:0] sumtree_22_V_fu_2023_p3;
wire   [9:0] sumtree_23_V_fu_2049_p3;
wire   [9:0] sumtree_24_V_fu_2075_p3;
wire   [9:0] sumtree_25_V_fu_2101_p3;
wire   [9:0] sumtree_26_V_fu_2127_p3;
wire   [9:0] sumtree_27_V_fu_2153_p3;
wire   [9:0] sumtree_28_V_fu_2179_p3;
wire   [9:0] sumtree_29_V_fu_2205_p3;
wire   [9:0] sumtree_30_V_fu_2231_p3;
wire   [9:0] sumtree_31_V_fu_2257_p3;
wire   [9:0] sumtree_32_V_fu_2283_p3;
wire   [9:0] sumtree_33_V_fu_2309_p3;
wire   [9:0] sumtree_34_V_fu_2335_p3;
wire   [9:0] sumtree_35_V_fu_2361_p3;
wire   [9:0] sumtree_36_V_fu_2387_p3;
wire   [9:0] sumtree_37_V_fu_2413_p3;
wire   [9:0] sumtree_38_V_fu_2439_p3;
wire   [9:0] sumtree_39_V_fu_2465_p3;
wire   [9:0] sumtree_40_V_fu_2491_p3;
wire   [9:0] sumtree_41_V_fu_2517_p3;
wire   [9:0] sumtree_42_V_fu_2543_p3;
wire   [9:0] sumtree_43_V_fu_2569_p3;
wire   [9:0] sumtree_44_V_fu_2595_p3;
wire   [9:0] sumtree_45_V_fu_2621_p3;
wire   [9:0] sumtree_46_V_fu_2647_p3;
wire   [9:0] sumtree_47_V_fu_2673_p3;
wire   [9:0] sumtree_48_V_fu_2699_p3;
wire   [9:0] sumtree_49_V_fu_2725_p3;
wire   [9:0] sumtree_50_V_fu_2751_p3;
wire   [9:0] sumtree_51_V_fu_2777_p3;
wire   [9:0] sumtree_52_V_fu_2803_p3;
wire   [9:0] sumtree_53_V_fu_2829_p3;
wire   [9:0] sumtree_54_V_fu_2855_p3;
wire   [9:0] sumtree_55_V_fu_2881_p3;
wire   [9:0] sumtree_56_V_fu_2907_p3;
wire   [9:0] sumtree_57_V_fu_2933_p3;
wire   [9:0] sumtree_58_V_fu_2959_p3;
wire   [9:0] sumtree_59_V_fu_2985_p3;
wire   [9:0] sumtree_60_V_fu_3011_p3;
wire   [9:0] sumtree_61_V_fu_3037_p3;
wire   [9:0] sumtree_62_V_fu_3063_p3;
wire   [9:0] sumtree_63_V_fu_3089_p3;
wire   [10:0] tmp_6_cast_fu_3097_p1;
wire   [10:0] tmp_6_1_cast_fu_3101_p1;
wire   [10:0] tmp4_fu_3353_p2;
wire   [10:0] tmp_6_2_cast_fu_3105_p1;
wire   [10:0] tmp_6_3_cast_fu_3109_p1;
wire   [10:0] tmp5_fu_3363_p2;
wire   [11:0] tmp5_cast_fu_3369_p1;
wire   [11:0] tmp4_cast_fu_3359_p1;
wire   [11:0] tmp3_fu_3373_p2;
wire   [10:0] tmp_6_4_cast_fu_3113_p1;
wire   [10:0] tmp_6_5_cast_fu_3117_p1;
wire   [10:0] tmp7_fu_3383_p2;
wire   [10:0] tmp_6_6_cast_fu_3121_p1;
wire   [10:0] tmp_6_7_cast_fu_3125_p1;
wire   [10:0] tmp8_fu_3393_p2;
wire   [11:0] tmp8_cast_fu_3399_p1;
wire   [11:0] tmp7_cast_fu_3389_p1;
wire   [11:0] tmp6_fu_3403_p2;
wire   [12:0] tmp6_cast_fu_3409_p1;
wire   [12:0] tmp3_cast_fu_3379_p1;
wire   [12:0] tmp2_fu_3413_p2;
wire   [10:0] tmp_6_8_cast_fu_3129_p1;
wire   [10:0] tmp_6_9_cast_fu_3133_p1;
wire   [10:0] tmp11_fu_3423_p2;
wire   [10:0] tmp_6_cast_13_fu_3137_p1;
wire   [10:0] tmp_6_10_cast_fu_3141_p1;
wire   [10:0] tmp12_fu_3433_p2;
wire   [11:0] tmp12_cast_fu_3439_p1;
wire   [11:0] tmp11_cast_fu_3429_p1;
wire   [11:0] tmp10_fu_3443_p2;
wire   [10:0] tmp_6_11_cast_fu_3145_p1;
wire   [10:0] tmp_6_12_cast_fu_3149_p1;
wire   [10:0] tmp14_fu_3453_p2;
wire   [10:0] tmp_6_13_cast_fu_3153_p1;
wire   [10:0] tmp_6_14_cast_fu_3157_p1;
wire   [10:0] tmp15_fu_3463_p2;
wire   [11:0] tmp15_cast_fu_3469_p1;
wire   [11:0] tmp14_cast_fu_3459_p1;
wire   [11:0] tmp13_fu_3473_p2;
wire   [12:0] tmp13_cast_fu_3479_p1;
wire   [12:0] tmp10_cast_fu_3449_p1;
wire   [12:0] tmp9_fu_3483_p2;
wire   [13:0] tmp9_cast_fu_3489_p1;
wire   [13:0] tmp2_cast_fu_3419_p1;
wire   [13:0] tmp1_fu_3493_p2;
wire   [10:0] tmp_6_15_cast_fu_3161_p1;
wire   [10:0] tmp_6_16_cast_fu_3165_p1;
wire   [10:0] tmp19_fu_3503_p2;
wire   [10:0] tmp_6_17_cast_fu_3169_p1;
wire   [10:0] tmp_6_18_cast_fu_3173_p1;
wire   [10:0] tmp20_fu_3513_p2;
wire   [11:0] tmp20_cast_fu_3519_p1;
wire   [11:0] tmp19_cast_fu_3509_p1;
wire   [11:0] tmp18_fu_3523_p2;
wire   [10:0] tmp_6_19_cast_fu_3177_p1;
wire   [10:0] tmp_6_20_cast_fu_3181_p1;
wire   [10:0] tmp22_fu_3533_p2;
wire   [10:0] tmp_6_21_cast_fu_3185_p1;
wire   [10:0] tmp_6_22_cast_fu_3189_p1;
wire   [10:0] tmp23_fu_3543_p2;
wire   [11:0] tmp23_cast_fu_3549_p1;
wire   [11:0] tmp22_cast_fu_3539_p1;
wire   [11:0] tmp21_fu_3553_p2;
wire   [12:0] tmp21_cast_fu_3559_p1;
wire   [12:0] tmp18_cast_fu_3529_p1;
wire   [12:0] tmp17_fu_3563_p2;
wire   [10:0] tmp_6_23_cast_fu_3193_p1;
wire   [10:0] tmp_6_24_cast_fu_3197_p1;
wire   [10:0] tmp26_fu_3573_p2;
wire   [10:0] tmp_6_25_cast_fu_3201_p1;
wire   [10:0] tmp_6_26_cast_fu_3205_p1;
wire   [10:0] tmp27_fu_3583_p2;
wire   [11:0] tmp27_cast_fu_3589_p1;
wire   [11:0] tmp26_cast_fu_3579_p1;
wire   [11:0] tmp25_fu_3593_p2;
wire   [10:0] tmp_6_27_cast_fu_3209_p1;
wire   [10:0] tmp_6_28_cast_fu_3213_p1;
wire   [10:0] tmp29_fu_3603_p2;
wire   [10:0] tmp_6_29_cast_fu_3217_p1;
wire   [10:0] tmp_6_30_cast_fu_3221_p1;
wire   [10:0] tmp30_fu_3613_p2;
wire   [11:0] tmp30_cast_fu_3619_p1;
wire   [11:0] tmp29_cast_fu_3609_p1;
wire   [11:0] tmp28_fu_3623_p2;
wire   [12:0] tmp28_cast_fu_3629_p1;
wire   [12:0] tmp25_cast_fu_3599_p1;
wire   [12:0] tmp24_fu_3633_p2;
wire   [13:0] tmp24_cast_fu_3639_p1;
wire   [13:0] tmp17_cast_fu_3569_p1;
wire   [13:0] tmp16_fu_3643_p2;
wire   [14:0] tmp16_cast_fu_3649_p1;
wire   [14:0] tmp1_cast_fu_3499_p1;
wire   [14:0] tmp_fu_3653_p2;
wire   [10:0] tmp_6_31_cast_fu_3225_p1;
wire   [10:0] tmp_6_32_cast_fu_3229_p1;
wire   [10:0] tmp35_fu_3663_p2;
wire   [10:0] tmp_6_33_cast_fu_3233_p1;
wire   [10:0] tmp_6_34_cast_fu_3237_p1;
wire   [10:0] tmp36_fu_3673_p2;
wire   [11:0] tmp36_cast_fu_3679_p1;
wire   [11:0] tmp35_cast_fu_3669_p1;
wire   [11:0] tmp34_fu_3683_p2;
wire   [10:0] tmp_6_35_cast_fu_3241_p1;
wire   [10:0] tmp_6_36_cast_fu_3245_p1;
wire   [10:0] tmp38_fu_3693_p2;
wire   [10:0] tmp_6_37_cast_fu_3249_p1;
wire   [10:0] tmp_6_38_cast_fu_3253_p1;
wire   [10:0] tmp39_fu_3703_p2;
wire   [11:0] tmp39_cast_fu_3709_p1;
wire   [11:0] tmp38_cast_fu_3699_p1;
wire   [11:0] tmp37_fu_3713_p2;
wire   [12:0] tmp37_cast_fu_3719_p1;
wire   [12:0] tmp34_cast_fu_3689_p1;
wire   [12:0] tmp33_fu_3723_p2;
wire   [10:0] tmp_6_39_cast_fu_3257_p1;
wire   [10:0] tmp_6_40_cast_fu_3261_p1;
wire   [10:0] tmp42_fu_3733_p2;
wire   [10:0] tmp_6_41_cast_fu_3265_p1;
wire   [10:0] tmp_6_42_cast_fu_3269_p1;
wire   [10:0] tmp43_fu_3743_p2;
wire   [11:0] tmp43_cast_fu_3749_p1;
wire   [11:0] tmp42_cast_fu_3739_p1;
wire   [11:0] tmp41_fu_3753_p2;
wire   [10:0] tmp_6_43_cast_fu_3273_p1;
wire   [10:0] tmp_6_44_cast_fu_3277_p1;
wire   [10:0] tmp45_fu_3763_p2;
wire   [10:0] tmp_6_45_cast_fu_3281_p1;
wire   [10:0] tmp_6_46_cast_fu_3285_p1;
wire   [10:0] tmp46_fu_3773_p2;
wire   [11:0] tmp46_cast_fu_3779_p1;
wire   [11:0] tmp45_cast_fu_3769_p1;
wire   [11:0] tmp44_fu_3783_p2;
wire   [12:0] tmp44_cast_fu_3789_p1;
wire   [12:0] tmp41_cast_fu_3759_p1;
wire   [12:0] tmp40_fu_3793_p2;
wire   [13:0] tmp40_cast_fu_3799_p1;
wire   [13:0] tmp33_cast_fu_3729_p1;
wire   [13:0] tmp32_fu_3803_p2;
wire   [10:0] tmp_6_47_cast_fu_3289_p1;
wire   [10:0] tmp_6_48_cast_fu_3293_p1;
wire   [10:0] tmp50_fu_3813_p2;
wire   [10:0] tmp_6_49_cast_fu_3297_p1;
wire   [10:0] tmp_6_50_cast_fu_3301_p1;
wire   [10:0] tmp51_fu_3823_p2;
wire   [11:0] tmp51_cast_fu_3829_p1;
wire   [11:0] tmp50_cast_fu_3819_p1;
wire   [11:0] tmp49_fu_3833_p2;
wire   [10:0] tmp_6_51_cast_fu_3305_p1;
wire   [10:0] tmp_6_52_cast_fu_3309_p1;
wire   [10:0] tmp53_fu_3843_p2;
wire   [10:0] tmp_6_53_cast_fu_3313_p1;
wire   [10:0] tmp_6_54_cast_fu_3317_p1;
wire   [10:0] tmp54_fu_3853_p2;
wire   [11:0] tmp54_cast_fu_3859_p1;
wire   [11:0] tmp53_cast_fu_3849_p1;
wire   [11:0] tmp52_fu_3863_p2;
wire   [12:0] tmp52_cast_fu_3869_p1;
wire   [12:0] tmp49_cast_fu_3839_p1;
wire   [12:0] tmp48_fu_3873_p2;
wire   [10:0] tmp_6_55_cast_fu_3321_p1;
wire   [10:0] tmp_6_56_cast_fu_3325_p1;
wire   [10:0] tmp57_fu_3883_p2;
wire   [10:0] tmp_6_57_cast_fu_3329_p1;
wire   [10:0] tmp_6_58_cast_fu_3333_p1;
wire   [10:0] tmp58_fu_3893_p2;
wire   [11:0] tmp58_cast_fu_3899_p1;
wire   [11:0] tmp57_cast_fu_3889_p1;
wire   [11:0] tmp56_fu_3903_p2;
wire   [10:0] tmp_6_59_cast_fu_3337_p1;
wire   [10:0] tmp_6_60_cast_fu_3341_p1;
wire   [10:0] tmp60_fu_3913_p2;
wire   [10:0] tmp_6_61_cast_fu_3345_p1;
wire   [10:0] tmp_6_62_cast_fu_3349_p1;
wire   [10:0] tmp61_fu_3923_p2;
wire   [11:0] tmp61_cast_fu_3929_p1;
wire   [11:0] tmp60_cast_fu_3919_p1;
wire   [11:0] tmp59_fu_3933_p2;
wire   [12:0] tmp59_cast_fu_3939_p1;
wire   [12:0] tmp56_cast_fu_3909_p1;
wire   [12:0] tmp55_fu_3943_p2;
wire   [13:0] tmp55_cast_fu_3949_p1;
wire   [13:0] tmp48_cast_fu_3879_p1;
wire   [13:0] tmp47_fu_3953_p2;
wire   [14:0] tmp47_cast_fu_3959_p1;
wire   [14:0] tmp32_cast_fu_3809_p1;
wire   [14:0] tmp31_fu_3963_p2;
wire   [15:0] tmp31_cast_fu_3969_p1;
wire   [15:0] tmp_cast_fu_3659_p1;
wire   [15:0] totalsum_V_s_fu_3973_p2;
reg   [3:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_reg_705 <= i_1_reg_4686;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_705 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((sumout_V_full_n == 1'b0) | (datain_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        datamem_10_V_fu_470 <= datamem_9_V_fu_466;
        datamem_11_V_fu_474 <= datamem_10_V_fu_470;
        datamem_12_V_fu_478 <= datamem_11_V_fu_474;
        datamem_13_V_fu_482 <= datamem_12_V_fu_478;
        datamem_14_V_fu_486 <= datamem_13_V_fu_482;
        datamem_15_V_fu_490 <= datamem_14_V_fu_486;
        datamem_16_V_fu_494 <= datamem_15_V_fu_490;
        datamem_17_V_fu_498 <= datamem_16_V_fu_494;
        datamem_18_V_fu_502 <= datamem_17_V_fu_498;
        datamem_19_V_fu_506 <= datamem_18_V_fu_502;
        datamem_1_V_fu_434 <= datain_V_dout;
        datamem_20_V_fu_510 <= datamem_19_V_fu_506;
        datamem_21_V_fu_514 <= datamem_20_V_fu_510;
        datamem_22_V_fu_518 <= datamem_21_V_fu_514;
        datamem_23_V_fu_522 <= datamem_22_V_fu_518;
        datamem_24_V_fu_526 <= datamem_23_V_fu_522;
        datamem_25_V_fu_530 <= datamem_24_V_fu_526;
        datamem_26_V_fu_534 <= datamem_25_V_fu_530;
        datamem_27_V_fu_538 <= datamem_26_V_fu_534;
        datamem_28_V_fu_542 <= datamem_27_V_fu_538;
        datamem_29_V_fu_546 <= datamem_28_V_fu_542;
        datamem_2_V_fu_438 <= datamem_1_V_fu_434;
        datamem_30_V_fu_550 <= datamem_29_V_fu_546;
        datamem_31_V_fu_554 <= datamem_30_V_fu_550;
        datamem_32_V_fu_558 <= datamem_31_V_fu_554;
        datamem_33_V_fu_562 <= datamem_32_V_fu_558;
        datamem_34_V_fu_566 <= datamem_33_V_fu_562;
        datamem_35_V_fu_570 <= datamem_34_V_fu_566;
        datamem_36_V_fu_574 <= datamem_35_V_fu_570;
        datamem_37_V_fu_578 <= datamem_36_V_fu_574;
        datamem_38_V_fu_582 <= datamem_37_V_fu_578;
        datamem_39_V_fu_586 <= datamem_38_V_fu_582;
        datamem_3_V_fu_442 <= datamem_2_V_fu_438;
        datamem_40_V_fu_590 <= datamem_39_V_fu_586;
        datamem_41_V_fu_594 <= datamem_40_V_fu_590;
        datamem_42_V_fu_598 <= datamem_41_V_fu_594;
        datamem_43_V_fu_602 <= datamem_42_V_fu_598;
        datamem_44_V_fu_606 <= datamem_43_V_fu_602;
        datamem_45_V_fu_610 <= datamem_44_V_fu_606;
        datamem_46_V_fu_614 <= datamem_45_V_fu_610;
        datamem_47_V_fu_618 <= datamem_46_V_fu_614;
        datamem_48_V_fu_622 <= datamem_47_V_fu_618;
        datamem_49_V_fu_626 <= datamem_48_V_fu_622;
        datamem_4_V_fu_446 <= datamem_3_V_fu_442;
        datamem_50_V_fu_630 <= datamem_49_V_fu_626;
        datamem_51_V_fu_634 <= datamem_50_V_fu_630;
        datamem_52_V_fu_638 <= datamem_51_V_fu_634;
        datamem_53_V_fu_642 <= datamem_52_V_fu_638;
        datamem_54_V_fu_646 <= datamem_53_V_fu_642;
        datamem_55_V_fu_650 <= datamem_54_V_fu_646;
        datamem_56_V_fu_654 <= datamem_55_V_fu_650;
        datamem_57_V_fu_658 <= datamem_56_V_fu_654;
        datamem_58_V_fu_662 <= datamem_57_V_fu_658;
        datamem_59_V_fu_666 <= datamem_58_V_fu_662;
        datamem_5_V_fu_450 <= datamem_4_V_fu_446;
        datamem_60_V_fu_670 <= datamem_59_V_fu_666;
        datamem_61_V_fu_674 <= datamem_60_V_fu_670;
        datamem_62_V_1_fu_682 <= datamem_62_V_fu_678;
        datamem_62_V_fu_678 <= datamem_61_V_fu_674;
        datamem_6_V_fu_454 <= datamem_5_V_fu_450;
        datamem_7_V_fu_458 <= datamem_6_V_fu_454;
        datamem_8_V_fu_462 <= datamem_7_V_fu_458;
        datamem_9_V_fu_466 <= datamem_8_V_fu_462;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        i_1_reg_4686 <= i_1_fu_722_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd10) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_10_fu_218 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd11) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_11_fu_222 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd12) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_12_fu_226 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd13) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_13_fu_230 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd14) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_14_fu_234 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd15) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_15_fu_238 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd16) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_16_fu_242 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd17) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_17_fu_246 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd18) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_18_fu_250 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd19) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_19_fu_254 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd1) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_1_fu_182 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd20) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_20_fu_258 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd21) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_21_fu_262 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd22) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_22_fu_266 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd23) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_23_fu_270 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd24) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_24_fu_274 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd25) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_25_fu_278 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd26) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_26_fu_282 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd27) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_27_fu_286 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd28) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_28_fu_290 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd29) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_29_fu_294 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd2) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_2_fu_186 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd30) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_30_fu_298 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd31) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_31_fu_302 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd32) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_32_fu_306 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd33) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_33_fu_310 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd34) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_34_fu_314 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd35) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_35_fu_318 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd36) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_36_fu_322 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd37) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_37_fu_326 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd38) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_38_fu_330 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd39) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_39_fu_334 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd3) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_3_fu_190 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd40) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_40_fu_338 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd41) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_41_fu_342 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd42) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_42_fu_346 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd43) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_43_fu_350 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd44) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_44_fu_354 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd45) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_45_fu_358 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd46) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_46_fu_362 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd47) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_47_fu_366 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd48) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_48_fu_370 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd49) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_49_fu_374 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd4) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_4_fu_194 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd50) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_50_fu_378 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd51) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_51_fu_382 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd52) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_52_fu_386 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd53) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_53_fu_390 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd54) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_54_fu_394 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd55) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_55_fu_398 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd56) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_56_fu_402 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd57) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_57_fu_406 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd58) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_58_fu_410 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd59) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_59_fu_414 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd5) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_5_fu_198 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd60) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_60_fu_418 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd61) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_61_fu_422 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd62) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_62_fu_426 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd63) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_63_fu_430 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd6) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_6_fu_202 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd7) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_7_fu_206 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd8) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_8_fu_210 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd9) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_9_fu_214 <= ref_points_in_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (tmp_3_fu_728_p1 == 6'd0) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_63_V_fu_178 <= ref_points_in_V_dout;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        datain_V_blk_n = datain_V_empty_n;
    end else begin
        datain_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((sumout_V_full_n == 1'b0) | (datain_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        datain_V_read = 1'b1;
    end else begin
        datain_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_in_V_blk_n = ref_points_in_V_empty_n;
    end else begin
        ref_points_in_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ref_points_in_V_read = 1'b1;
    end else begin
        ref_points_in_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        sumout_V_blk_n = sumout_V_full_n;
    end else begin
        sumout_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((sumout_V_full_n == 1'b0) | (datain_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        sumout_V_write = 1'b1;
    end else begin
        sumout_V_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (exitcond1_fu_716_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if ((~((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0)) & (exitcond1_fu_716_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state2 = ((exitcond1_fu_716_p2 == 1'd0) & (ref_points_in_V_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state4 = ((sumout_V_full_n == 1'b0) | (datain_V_empty_n == 1'b0));
end

assign ap_done = 1'b0;

assign ap_ready = 1'b0;

assign exitcond1_fu_716_p2 = ((i_reg_705 == 7'd64) ? 1'b1 : 1'b0);

assign i_1_fu_722_p2 = (i_reg_705 + 7'd1);

assign sumout_V_din = totalsum_V_s_fu_3973_p2;

assign sumtree_0_V_fu_1451_p3 = ((tmp_9_fu_1433_p2[0:0] === 1'b1) ? tmp_s_fu_1439_p2 : tmp_2_fu_1445_p2);

assign sumtree_10_V_fu_1711_p3 = ((tmp_9_s_fu_1693_p2[0:0] === 1'b1) ? tmp_s_11_fu_1699_p2 : tmp_1_s_fu_1705_p2);

assign sumtree_11_V_fu_1737_p3 = ((tmp_9_10_12_fu_1719_p2[0:0] === 1'b1) ? tmp_10_fu_1725_p2 : tmp_1_10_fu_1731_p2);

assign sumtree_12_V_fu_1763_p3 = ((tmp_9_11_fu_1745_p2[0:0] === 1'b1) ? tmp_11_fu_1751_p2 : tmp_1_11_fu_1757_p2);

assign sumtree_13_V_fu_1789_p3 = ((tmp_9_12_fu_1771_p2[0:0] === 1'b1) ? tmp_12_fu_1777_p2 : tmp_1_12_fu_1783_p2);

assign sumtree_14_V_fu_1815_p3 = ((tmp_9_13_fu_1797_p2[0:0] === 1'b1) ? tmp_13_fu_1803_p2 : tmp_1_13_fu_1809_p2);

assign sumtree_15_V_fu_1841_p3 = ((tmp_9_14_fu_1823_p2[0:0] === 1'b1) ? tmp_14_fu_1829_p2 : tmp_1_14_fu_1835_p2);

assign sumtree_16_V_fu_1867_p3 = ((tmp_9_15_fu_1849_p2[0:0] === 1'b1) ? tmp_15_fu_1855_p2 : tmp_1_15_fu_1861_p2);

assign sumtree_17_V_fu_1893_p3 = ((tmp_9_16_fu_1875_p2[0:0] === 1'b1) ? tmp_16_fu_1881_p2 : tmp_1_16_fu_1887_p2);

assign sumtree_18_V_fu_1919_p3 = ((tmp_9_17_fu_1901_p2[0:0] === 1'b1) ? tmp_17_fu_1907_p2 : tmp_1_17_fu_1913_p2);

assign sumtree_19_V_fu_1945_p3 = ((tmp_9_18_fu_1927_p2[0:0] === 1'b1) ? tmp_18_fu_1933_p2 : tmp_1_18_fu_1939_p2);

assign sumtree_1_V_fu_1477_p3 = ((tmp_9_1_fu_1459_p2[0:0] === 1'b1) ? tmp_1_4_fu_1465_p2 : tmp_1_1_fu_1471_p2);

assign sumtree_20_V_fu_1971_p3 = ((tmp_9_19_fu_1953_p2[0:0] === 1'b1) ? tmp_19_fu_1959_p2 : tmp_1_19_fu_1965_p2);

assign sumtree_21_V_fu_1997_p3 = ((tmp_9_20_fu_1979_p2[0:0] === 1'b1) ? tmp_20_fu_1985_p2 : tmp_1_20_fu_1991_p2);

assign sumtree_22_V_fu_2023_p3 = ((tmp_9_21_fu_2005_p2[0:0] === 1'b1) ? tmp_21_fu_2011_p2 : tmp_1_21_fu_2017_p2);

assign sumtree_23_V_fu_2049_p3 = ((tmp_9_22_fu_2031_p2[0:0] === 1'b1) ? tmp_22_fu_2037_p2 : tmp_1_22_fu_2043_p2);

assign sumtree_24_V_fu_2075_p3 = ((tmp_9_23_fu_2057_p2[0:0] === 1'b1) ? tmp_23_fu_2063_p2 : tmp_1_23_fu_2069_p2);

assign sumtree_25_V_fu_2101_p3 = ((tmp_9_24_fu_2083_p2[0:0] === 1'b1) ? tmp_24_fu_2089_p2 : tmp_1_24_fu_2095_p2);

assign sumtree_26_V_fu_2127_p3 = ((tmp_9_25_fu_2109_p2[0:0] === 1'b1) ? tmp_25_fu_2115_p2 : tmp_1_25_fu_2121_p2);

assign sumtree_27_V_fu_2153_p3 = ((tmp_9_26_fu_2135_p2[0:0] === 1'b1) ? tmp_26_fu_2141_p2 : tmp_1_26_fu_2147_p2);

assign sumtree_28_V_fu_2179_p3 = ((tmp_9_27_fu_2161_p2[0:0] === 1'b1) ? tmp_27_fu_2167_p2 : tmp_1_27_fu_2173_p2);

assign sumtree_29_V_fu_2205_p3 = ((tmp_9_28_fu_2187_p2[0:0] === 1'b1) ? tmp_28_fu_2193_p2 : tmp_1_28_fu_2199_p2);

assign sumtree_2_V_fu_1503_p3 = ((tmp_9_2_fu_1485_p2[0:0] === 1'b1) ? tmp_2_5_fu_1491_p2 : tmp_1_2_fu_1497_p2);

assign sumtree_30_V_fu_2231_p3 = ((tmp_9_29_fu_2213_p2[0:0] === 1'b1) ? tmp_29_fu_2219_p2 : tmp_1_29_fu_2225_p2);

assign sumtree_31_V_fu_2257_p3 = ((tmp_9_30_fu_2239_p2[0:0] === 1'b1) ? tmp_30_fu_2245_p2 : tmp_1_30_fu_2251_p2);

assign sumtree_32_V_fu_2283_p3 = ((tmp_9_31_fu_2265_p2[0:0] === 1'b1) ? tmp_31_fu_2271_p2 : tmp_1_31_fu_2277_p2);

assign sumtree_33_V_fu_2309_p3 = ((tmp_9_32_fu_2291_p2[0:0] === 1'b1) ? tmp_32_fu_2297_p2 : tmp_1_32_fu_2303_p2);

assign sumtree_34_V_fu_2335_p3 = ((tmp_9_33_fu_2317_p2[0:0] === 1'b1) ? tmp_33_fu_2323_p2 : tmp_1_33_fu_2329_p2);

assign sumtree_35_V_fu_2361_p3 = ((tmp_9_34_fu_2343_p2[0:0] === 1'b1) ? tmp_34_fu_2349_p2 : tmp_1_34_fu_2355_p2);

assign sumtree_36_V_fu_2387_p3 = ((tmp_9_35_fu_2369_p2[0:0] === 1'b1) ? tmp_35_fu_2375_p2 : tmp_1_35_fu_2381_p2);

assign sumtree_37_V_fu_2413_p3 = ((tmp_9_36_fu_2395_p2[0:0] === 1'b1) ? tmp_36_fu_2401_p2 : tmp_1_36_fu_2407_p2);

assign sumtree_38_V_fu_2439_p3 = ((tmp_9_37_fu_2421_p2[0:0] === 1'b1) ? tmp_37_fu_2427_p2 : tmp_1_37_fu_2433_p2);

assign sumtree_39_V_fu_2465_p3 = ((tmp_9_38_fu_2447_p2[0:0] === 1'b1) ? tmp_38_fu_2453_p2 : tmp_1_38_fu_2459_p2);

assign sumtree_3_V_fu_1529_p3 = ((tmp_9_3_fu_1511_p2[0:0] === 1'b1) ? tmp_3_6_fu_1517_p2 : tmp_1_3_fu_1523_p2);

assign sumtree_40_V_fu_2491_p3 = ((tmp_9_39_fu_2473_p2[0:0] === 1'b1) ? tmp_39_fu_2479_p2 : tmp_1_39_fu_2485_p2);

assign sumtree_41_V_fu_2517_p3 = ((tmp_9_40_fu_2499_p2[0:0] === 1'b1) ? tmp_40_fu_2505_p2 : tmp_1_40_fu_2511_p2);

assign sumtree_42_V_fu_2543_p3 = ((tmp_9_41_fu_2525_p2[0:0] === 1'b1) ? tmp_41_fu_2531_p2 : tmp_1_41_fu_2537_p2);

assign sumtree_43_V_fu_2569_p3 = ((tmp_9_42_fu_2551_p2[0:0] === 1'b1) ? tmp_42_fu_2557_p2 : tmp_1_42_fu_2563_p2);

assign sumtree_44_V_fu_2595_p3 = ((tmp_9_43_fu_2577_p2[0:0] === 1'b1) ? tmp_43_fu_2583_p2 : tmp_1_43_fu_2589_p2);

assign sumtree_45_V_fu_2621_p3 = ((tmp_9_44_fu_2603_p2[0:0] === 1'b1) ? tmp_44_fu_2609_p2 : tmp_1_44_fu_2615_p2);

assign sumtree_46_V_fu_2647_p3 = ((tmp_9_45_fu_2629_p2[0:0] === 1'b1) ? tmp_45_fu_2635_p2 : tmp_1_45_fu_2641_p2);

assign sumtree_47_V_fu_2673_p3 = ((tmp_9_46_fu_2655_p2[0:0] === 1'b1) ? tmp_46_fu_2661_p2 : tmp_1_46_fu_2667_p2);

assign sumtree_48_V_fu_2699_p3 = ((tmp_9_47_fu_2681_p2[0:0] === 1'b1) ? tmp_47_fu_2687_p2 : tmp_1_47_fu_2693_p2);

assign sumtree_49_V_fu_2725_p3 = ((tmp_9_48_fu_2707_p2[0:0] === 1'b1) ? tmp_48_fu_2713_p2 : tmp_1_48_fu_2719_p2);

assign sumtree_4_V_fu_1555_p3 = ((tmp_9_4_fu_1537_p2[0:0] === 1'b1) ? tmp_4_fu_1543_p2 : tmp_1_4_7_fu_1549_p2);

assign sumtree_50_V_fu_2751_p3 = ((tmp_9_49_fu_2733_p2[0:0] === 1'b1) ? tmp_49_fu_2739_p2 : tmp_1_49_fu_2745_p2);

assign sumtree_51_V_fu_2777_p3 = ((tmp_9_50_fu_2759_p2[0:0] === 1'b1) ? tmp_50_fu_2765_p2 : tmp_1_50_fu_2771_p2);

assign sumtree_52_V_fu_2803_p3 = ((tmp_9_51_fu_2785_p2[0:0] === 1'b1) ? tmp_51_fu_2791_p2 : tmp_1_51_fu_2797_p2);

assign sumtree_53_V_fu_2829_p3 = ((tmp_9_52_fu_2811_p2[0:0] === 1'b1) ? tmp_52_fu_2817_p2 : tmp_1_52_fu_2823_p2);

assign sumtree_54_V_fu_2855_p3 = ((tmp_9_53_fu_2837_p2[0:0] === 1'b1) ? tmp_53_fu_2843_p2 : tmp_1_53_fu_2849_p2);

assign sumtree_55_V_fu_2881_p3 = ((tmp_9_54_fu_2863_p2[0:0] === 1'b1) ? tmp_54_fu_2869_p2 : tmp_1_54_fu_2875_p2);

assign sumtree_56_V_fu_2907_p3 = ((tmp_9_55_fu_2889_p2[0:0] === 1'b1) ? tmp_55_fu_2895_p2 : tmp_1_55_fu_2901_p2);

assign sumtree_57_V_fu_2933_p3 = ((tmp_9_56_fu_2915_p2[0:0] === 1'b1) ? tmp_56_fu_2921_p2 : tmp_1_56_fu_2927_p2);

assign sumtree_58_V_fu_2959_p3 = ((tmp_9_57_fu_2941_p2[0:0] === 1'b1) ? tmp_57_fu_2947_p2 : tmp_1_57_fu_2953_p2);

assign sumtree_59_V_fu_2985_p3 = ((tmp_9_58_fu_2967_p2[0:0] === 1'b1) ? tmp_58_fu_2973_p2 : tmp_1_58_fu_2979_p2);

assign sumtree_5_V_fu_1581_p3 = ((tmp_9_5_fu_1563_p2[0:0] === 1'b1) ? tmp_5_fu_1569_p2 : tmp_1_5_fu_1575_p2);

assign sumtree_60_V_fu_3011_p3 = ((tmp_9_59_fu_2993_p2[0:0] === 1'b1) ? tmp_59_fu_2999_p2 : tmp_1_59_fu_3005_p2);

assign sumtree_61_V_fu_3037_p3 = ((tmp_9_60_fu_3019_p2[0:0] === 1'b1) ? tmp_60_fu_3025_p2 : tmp_1_60_fu_3031_p2);

assign sumtree_62_V_fu_3063_p3 = ((tmp_9_61_fu_3045_p2[0:0] === 1'b1) ? tmp_61_fu_3051_p2 : tmp_1_61_fu_3057_p2);

assign sumtree_63_V_fu_3089_p3 = ((tmp_9_62_fu_3071_p2[0:0] === 1'b1) ? tmp_62_fu_3077_p2 : tmp_1_62_fu_3083_p2);

assign sumtree_6_V_fu_1607_p3 = ((tmp_9_6_fu_1589_p2[0:0] === 1'b1) ? tmp_6_fu_1595_p2 : tmp_1_6_fu_1601_p2);

assign sumtree_7_V_fu_1633_p3 = ((tmp_9_7_fu_1615_p2[0:0] === 1'b1) ? tmp_7_fu_1621_p2 : tmp_1_7_fu_1627_p2);

assign sumtree_8_V_fu_1659_p3 = ((tmp_9_8_fu_1641_p2[0:0] === 1'b1) ? tmp_8_fu_1647_p2 : tmp_1_8_fu_1653_p2);

assign sumtree_9_V_fu_1685_p3 = ((tmp_9_9_fu_1667_p2[0:0] === 1'b1) ? tmp_9_10_fu_1673_p2 : tmp_1_9_fu_1679_p2);

assign tmp10_cast_fu_3449_p1 = tmp10_fu_3443_p2;

assign tmp10_fu_3443_p2 = (tmp12_cast_fu_3439_p1 + tmp11_cast_fu_3429_p1);

assign tmp11_cast_fu_3429_p1 = tmp11_fu_3423_p2;

assign tmp11_fu_3423_p2 = (tmp_6_8_cast_fu_3129_p1 + tmp_6_9_cast_fu_3133_p1);

assign tmp12_cast_fu_3439_p1 = tmp12_fu_3433_p2;

assign tmp12_fu_3433_p2 = (tmp_6_cast_13_fu_3137_p1 + tmp_6_10_cast_fu_3141_p1);

assign tmp13_cast_fu_3479_p1 = tmp13_fu_3473_p2;

assign tmp13_fu_3473_p2 = (tmp15_cast_fu_3469_p1 + tmp14_cast_fu_3459_p1);

assign tmp14_cast_fu_3459_p1 = tmp14_fu_3453_p2;

assign tmp14_fu_3453_p2 = (tmp_6_11_cast_fu_3145_p1 + tmp_6_12_cast_fu_3149_p1);

assign tmp15_cast_fu_3469_p1 = tmp15_fu_3463_p2;

assign tmp15_fu_3463_p2 = (tmp_6_13_cast_fu_3153_p1 + tmp_6_14_cast_fu_3157_p1);

assign tmp16_cast_fu_3649_p1 = tmp16_fu_3643_p2;

assign tmp16_fu_3643_p2 = (tmp24_cast_fu_3639_p1 + tmp17_cast_fu_3569_p1);

assign tmp17_cast_fu_3569_p1 = tmp17_fu_3563_p2;

assign tmp17_fu_3563_p2 = (tmp21_cast_fu_3559_p1 + tmp18_cast_fu_3529_p1);

assign tmp18_cast_fu_3529_p1 = tmp18_fu_3523_p2;

assign tmp18_fu_3523_p2 = (tmp20_cast_fu_3519_p1 + tmp19_cast_fu_3509_p1);

assign tmp19_cast_fu_3509_p1 = tmp19_fu_3503_p2;

assign tmp19_fu_3503_p2 = (tmp_6_15_cast_fu_3161_p1 + tmp_6_16_cast_fu_3165_p1);

assign tmp1_cast_fu_3499_p1 = tmp1_fu_3493_p2;

assign tmp1_fu_3493_p2 = (tmp9_cast_fu_3489_p1 + tmp2_cast_fu_3419_p1);

assign tmp20_cast_fu_3519_p1 = tmp20_fu_3513_p2;

assign tmp20_fu_3513_p2 = (tmp_6_17_cast_fu_3169_p1 + tmp_6_18_cast_fu_3173_p1);

assign tmp21_cast_fu_3559_p1 = tmp21_fu_3553_p2;

assign tmp21_fu_3553_p2 = (tmp23_cast_fu_3549_p1 + tmp22_cast_fu_3539_p1);

assign tmp22_cast_fu_3539_p1 = tmp22_fu_3533_p2;

assign tmp22_fu_3533_p2 = (tmp_6_19_cast_fu_3177_p1 + tmp_6_20_cast_fu_3181_p1);

assign tmp23_cast_fu_3549_p1 = tmp23_fu_3543_p2;

assign tmp23_fu_3543_p2 = (tmp_6_21_cast_fu_3185_p1 + tmp_6_22_cast_fu_3189_p1);

assign tmp24_cast_fu_3639_p1 = tmp24_fu_3633_p2;

assign tmp24_fu_3633_p2 = (tmp28_cast_fu_3629_p1 + tmp25_cast_fu_3599_p1);

assign tmp25_cast_fu_3599_p1 = tmp25_fu_3593_p2;

assign tmp25_fu_3593_p2 = (tmp27_cast_fu_3589_p1 + tmp26_cast_fu_3579_p1);

assign tmp26_cast_fu_3579_p1 = tmp26_fu_3573_p2;

assign tmp26_fu_3573_p2 = (tmp_6_23_cast_fu_3193_p1 + tmp_6_24_cast_fu_3197_p1);

assign tmp27_cast_fu_3589_p1 = tmp27_fu_3583_p2;

assign tmp27_fu_3583_p2 = (tmp_6_25_cast_fu_3201_p1 + tmp_6_26_cast_fu_3205_p1);

assign tmp28_cast_fu_3629_p1 = tmp28_fu_3623_p2;

assign tmp28_fu_3623_p2 = (tmp30_cast_fu_3619_p1 + tmp29_cast_fu_3609_p1);

assign tmp29_cast_fu_3609_p1 = tmp29_fu_3603_p2;

assign tmp29_fu_3603_p2 = (tmp_6_27_cast_fu_3209_p1 + tmp_6_28_cast_fu_3213_p1);

assign tmp2_cast_fu_3419_p1 = tmp2_fu_3413_p2;

assign tmp2_fu_3413_p2 = (tmp6_cast_fu_3409_p1 + tmp3_cast_fu_3379_p1);

assign tmp30_cast_fu_3619_p1 = tmp30_fu_3613_p2;

assign tmp30_fu_3613_p2 = (tmp_6_29_cast_fu_3217_p1 + tmp_6_30_cast_fu_3221_p1);

assign tmp31_cast_fu_3969_p1 = tmp31_fu_3963_p2;

assign tmp31_fu_3963_p2 = (tmp47_cast_fu_3959_p1 + tmp32_cast_fu_3809_p1);

assign tmp32_cast_fu_3809_p1 = tmp32_fu_3803_p2;

assign tmp32_fu_3803_p2 = (tmp40_cast_fu_3799_p1 + tmp33_cast_fu_3729_p1);

assign tmp33_cast_fu_3729_p1 = tmp33_fu_3723_p2;

assign tmp33_fu_3723_p2 = (tmp37_cast_fu_3719_p1 + tmp34_cast_fu_3689_p1);

assign tmp34_cast_fu_3689_p1 = tmp34_fu_3683_p2;

assign tmp34_fu_3683_p2 = (tmp36_cast_fu_3679_p1 + tmp35_cast_fu_3669_p1);

assign tmp35_cast_fu_3669_p1 = tmp35_fu_3663_p2;

assign tmp35_fu_3663_p2 = (tmp_6_31_cast_fu_3225_p1 + tmp_6_32_cast_fu_3229_p1);

assign tmp36_cast_fu_3679_p1 = tmp36_fu_3673_p2;

assign tmp36_fu_3673_p2 = (tmp_6_33_cast_fu_3233_p1 + tmp_6_34_cast_fu_3237_p1);

assign tmp37_cast_fu_3719_p1 = tmp37_fu_3713_p2;

assign tmp37_fu_3713_p2 = (tmp39_cast_fu_3709_p1 + tmp38_cast_fu_3699_p1);

assign tmp38_cast_fu_3699_p1 = tmp38_fu_3693_p2;

assign tmp38_fu_3693_p2 = (tmp_6_35_cast_fu_3241_p1 + tmp_6_36_cast_fu_3245_p1);

assign tmp39_cast_fu_3709_p1 = tmp39_fu_3703_p2;

assign tmp39_fu_3703_p2 = (tmp_6_37_cast_fu_3249_p1 + tmp_6_38_cast_fu_3253_p1);

assign tmp3_cast_fu_3379_p1 = tmp3_fu_3373_p2;

assign tmp3_fu_3373_p2 = (tmp5_cast_fu_3369_p1 + tmp4_cast_fu_3359_p1);

assign tmp40_cast_fu_3799_p1 = tmp40_fu_3793_p2;

assign tmp40_fu_3793_p2 = (tmp44_cast_fu_3789_p1 + tmp41_cast_fu_3759_p1);

assign tmp41_cast_fu_3759_p1 = tmp41_fu_3753_p2;

assign tmp41_fu_3753_p2 = (tmp43_cast_fu_3749_p1 + tmp42_cast_fu_3739_p1);

assign tmp42_cast_fu_3739_p1 = tmp42_fu_3733_p2;

assign tmp42_fu_3733_p2 = (tmp_6_39_cast_fu_3257_p1 + tmp_6_40_cast_fu_3261_p1);

assign tmp43_cast_fu_3749_p1 = tmp43_fu_3743_p2;

assign tmp43_fu_3743_p2 = (tmp_6_41_cast_fu_3265_p1 + tmp_6_42_cast_fu_3269_p1);

assign tmp44_cast_fu_3789_p1 = tmp44_fu_3783_p2;

assign tmp44_fu_3783_p2 = (tmp46_cast_fu_3779_p1 + tmp45_cast_fu_3769_p1);

assign tmp45_cast_fu_3769_p1 = tmp45_fu_3763_p2;

assign tmp45_fu_3763_p2 = (tmp_6_43_cast_fu_3273_p1 + tmp_6_44_cast_fu_3277_p1);

assign tmp46_cast_fu_3779_p1 = tmp46_fu_3773_p2;

assign tmp46_fu_3773_p2 = (tmp_6_45_cast_fu_3281_p1 + tmp_6_46_cast_fu_3285_p1);

assign tmp47_cast_fu_3959_p1 = tmp47_fu_3953_p2;

assign tmp47_fu_3953_p2 = (tmp55_cast_fu_3949_p1 + tmp48_cast_fu_3879_p1);

assign tmp48_cast_fu_3879_p1 = tmp48_fu_3873_p2;

assign tmp48_fu_3873_p2 = (tmp52_cast_fu_3869_p1 + tmp49_cast_fu_3839_p1);

assign tmp49_cast_fu_3839_p1 = tmp49_fu_3833_p2;

assign tmp49_fu_3833_p2 = (tmp51_cast_fu_3829_p1 + tmp50_cast_fu_3819_p1);

assign tmp4_cast_fu_3359_p1 = tmp4_fu_3353_p2;

assign tmp4_fu_3353_p2 = (tmp_6_cast_fu_3097_p1 + tmp_6_1_cast_fu_3101_p1);

assign tmp50_cast_fu_3819_p1 = tmp50_fu_3813_p2;

assign tmp50_fu_3813_p2 = (tmp_6_47_cast_fu_3289_p1 + tmp_6_48_cast_fu_3293_p1);

assign tmp51_cast_fu_3829_p1 = tmp51_fu_3823_p2;

assign tmp51_fu_3823_p2 = (tmp_6_49_cast_fu_3297_p1 + tmp_6_50_cast_fu_3301_p1);

assign tmp52_cast_fu_3869_p1 = tmp52_fu_3863_p2;

assign tmp52_fu_3863_p2 = (tmp54_cast_fu_3859_p1 + tmp53_cast_fu_3849_p1);

assign tmp53_cast_fu_3849_p1 = tmp53_fu_3843_p2;

assign tmp53_fu_3843_p2 = (tmp_6_51_cast_fu_3305_p1 + tmp_6_52_cast_fu_3309_p1);

assign tmp54_cast_fu_3859_p1 = tmp54_fu_3853_p2;

assign tmp54_fu_3853_p2 = (tmp_6_53_cast_fu_3313_p1 + tmp_6_54_cast_fu_3317_p1);

assign tmp55_cast_fu_3949_p1 = tmp55_fu_3943_p2;

assign tmp55_fu_3943_p2 = (tmp59_cast_fu_3939_p1 + tmp56_cast_fu_3909_p1);

assign tmp56_cast_fu_3909_p1 = tmp56_fu_3903_p2;

assign tmp56_fu_3903_p2 = (tmp58_cast_fu_3899_p1 + tmp57_cast_fu_3889_p1);

assign tmp57_cast_fu_3889_p1 = tmp57_fu_3883_p2;

assign tmp57_fu_3883_p2 = (tmp_6_55_cast_fu_3321_p1 + tmp_6_56_cast_fu_3325_p1);

assign tmp58_cast_fu_3899_p1 = tmp58_fu_3893_p2;

assign tmp58_fu_3893_p2 = (tmp_6_57_cast_fu_3329_p1 + tmp_6_58_cast_fu_3333_p1);

assign tmp59_cast_fu_3939_p1 = tmp59_fu_3933_p2;

assign tmp59_fu_3933_p2 = (tmp61_cast_fu_3929_p1 + tmp60_cast_fu_3919_p1);

assign tmp5_cast_fu_3369_p1 = tmp5_fu_3363_p2;

assign tmp5_fu_3363_p2 = (tmp_6_2_cast_fu_3105_p1 + tmp_6_3_cast_fu_3109_p1);

assign tmp60_cast_fu_3919_p1 = tmp60_fu_3913_p2;

assign tmp60_fu_3913_p2 = (tmp_6_59_cast_fu_3337_p1 + tmp_6_60_cast_fu_3341_p1);

assign tmp61_cast_fu_3929_p1 = tmp61_fu_3923_p2;

assign tmp61_fu_3923_p2 = (tmp_6_61_cast_fu_3345_p1 + tmp_6_62_cast_fu_3349_p1);

assign tmp6_cast_fu_3409_p1 = tmp6_fu_3403_p2;

assign tmp6_fu_3403_p2 = (tmp8_cast_fu_3399_p1 + tmp7_cast_fu_3389_p1);

assign tmp7_cast_fu_3389_p1 = tmp7_fu_3383_p2;

assign tmp7_fu_3383_p2 = (tmp_6_4_cast_fu_3113_p1 + tmp_6_5_cast_fu_3117_p1);

assign tmp8_cast_fu_3399_p1 = tmp8_fu_3393_p2;

assign tmp8_fu_3393_p2 = (tmp_6_6_cast_fu_3121_p1 + tmp_6_7_cast_fu_3125_p1);

assign tmp9_cast_fu_3489_p1 = tmp9_fu_3483_p2;

assign tmp9_fu_3483_p2 = (tmp13_cast_fu_3479_p1 + tmp10_cast_fu_3449_p1);

assign tmp_10_fu_1725_p2 = (datamem_11_V_fu_474 - ref_points_63_V_11_fu_222);

assign tmp_11_fu_1751_p2 = (datamem_12_V_fu_478 - ref_points_63_V_12_fu_226);

assign tmp_12_fu_1777_p2 = (datamem_13_V_fu_482 - ref_points_63_V_13_fu_230);

assign tmp_13_fu_1803_p2 = (datamem_14_V_fu_486 - ref_points_63_V_14_fu_234);

assign tmp_14_fu_1829_p2 = (datamem_15_V_fu_490 - ref_points_63_V_15_fu_238);

assign tmp_15_fu_1855_p2 = (datamem_16_V_fu_494 - ref_points_63_V_16_fu_242);

assign tmp_16_fu_1881_p2 = (datamem_17_V_fu_498 - ref_points_63_V_17_fu_246);

assign tmp_17_fu_1907_p2 = (datamem_18_V_fu_502 - ref_points_63_V_18_fu_250);

assign tmp_18_fu_1933_p2 = (datamem_19_V_fu_506 - ref_points_63_V_19_fu_254);

assign tmp_19_fu_1959_p2 = (datamem_20_V_fu_510 - ref_points_63_V_20_fu_258);

assign tmp_1_10_fu_1731_p2 = (ref_points_63_V_11_fu_222 - datamem_11_V_fu_474);

assign tmp_1_11_fu_1757_p2 = (ref_points_63_V_12_fu_226 - datamem_12_V_fu_478);

assign tmp_1_12_fu_1783_p2 = (ref_points_63_V_13_fu_230 - datamem_13_V_fu_482);

assign tmp_1_13_fu_1809_p2 = (ref_points_63_V_14_fu_234 - datamem_14_V_fu_486);

assign tmp_1_14_fu_1835_p2 = (ref_points_63_V_15_fu_238 - datamem_15_V_fu_490);

assign tmp_1_15_fu_1861_p2 = (ref_points_63_V_16_fu_242 - datamem_16_V_fu_494);

assign tmp_1_16_fu_1887_p2 = (ref_points_63_V_17_fu_246 - datamem_17_V_fu_498);

assign tmp_1_17_fu_1913_p2 = (ref_points_63_V_18_fu_250 - datamem_18_V_fu_502);

assign tmp_1_18_fu_1939_p2 = (ref_points_63_V_19_fu_254 - datamem_19_V_fu_506);

assign tmp_1_19_fu_1965_p2 = (ref_points_63_V_20_fu_258 - datamem_20_V_fu_510);

assign tmp_1_1_fu_1471_p2 = (ref_points_63_V_1_fu_182 - datamem_1_V_fu_434);

assign tmp_1_20_fu_1991_p2 = (ref_points_63_V_21_fu_262 - datamem_21_V_fu_514);

assign tmp_1_21_fu_2017_p2 = (ref_points_63_V_22_fu_266 - datamem_22_V_fu_518);

assign tmp_1_22_fu_2043_p2 = (ref_points_63_V_23_fu_270 - datamem_23_V_fu_522);

assign tmp_1_23_fu_2069_p2 = (ref_points_63_V_24_fu_274 - datamem_24_V_fu_526);

assign tmp_1_24_fu_2095_p2 = (ref_points_63_V_25_fu_278 - datamem_25_V_fu_530);

assign tmp_1_25_fu_2121_p2 = (ref_points_63_V_26_fu_282 - datamem_26_V_fu_534);

assign tmp_1_26_fu_2147_p2 = (ref_points_63_V_27_fu_286 - datamem_27_V_fu_538);

assign tmp_1_27_fu_2173_p2 = (ref_points_63_V_28_fu_290 - datamem_28_V_fu_542);

assign tmp_1_28_fu_2199_p2 = (ref_points_63_V_29_fu_294 - datamem_29_V_fu_546);

assign tmp_1_29_fu_2225_p2 = (ref_points_63_V_30_fu_298 - datamem_30_V_fu_550);

assign tmp_1_2_fu_1497_p2 = (ref_points_63_V_2_fu_186 - datamem_2_V_fu_438);

assign tmp_1_30_fu_2251_p2 = (ref_points_63_V_31_fu_302 - datamem_31_V_fu_554);

assign tmp_1_31_fu_2277_p2 = (ref_points_63_V_32_fu_306 - datamem_32_V_fu_558);

assign tmp_1_32_fu_2303_p2 = (ref_points_63_V_33_fu_310 - datamem_33_V_fu_562);

assign tmp_1_33_fu_2329_p2 = (ref_points_63_V_34_fu_314 - datamem_34_V_fu_566);

assign tmp_1_34_fu_2355_p2 = (ref_points_63_V_35_fu_318 - datamem_35_V_fu_570);

assign tmp_1_35_fu_2381_p2 = (ref_points_63_V_36_fu_322 - datamem_36_V_fu_574);

assign tmp_1_36_fu_2407_p2 = (ref_points_63_V_37_fu_326 - datamem_37_V_fu_578);

assign tmp_1_37_fu_2433_p2 = (ref_points_63_V_38_fu_330 - datamem_38_V_fu_582);

assign tmp_1_38_fu_2459_p2 = (ref_points_63_V_39_fu_334 - datamem_39_V_fu_586);

assign tmp_1_39_fu_2485_p2 = (ref_points_63_V_40_fu_338 - datamem_40_V_fu_590);

assign tmp_1_3_fu_1523_p2 = (ref_points_63_V_3_fu_190 - datamem_3_V_fu_442);

assign tmp_1_40_fu_2511_p2 = (ref_points_63_V_41_fu_342 - datamem_41_V_fu_594);

assign tmp_1_41_fu_2537_p2 = (ref_points_63_V_42_fu_346 - datamem_42_V_fu_598);

assign tmp_1_42_fu_2563_p2 = (ref_points_63_V_43_fu_350 - datamem_43_V_fu_602);

assign tmp_1_43_fu_2589_p2 = (ref_points_63_V_44_fu_354 - datamem_44_V_fu_606);

assign tmp_1_44_fu_2615_p2 = (ref_points_63_V_45_fu_358 - datamem_45_V_fu_610);

assign tmp_1_45_fu_2641_p2 = (ref_points_63_V_46_fu_362 - datamem_46_V_fu_614);

assign tmp_1_46_fu_2667_p2 = (ref_points_63_V_47_fu_366 - datamem_47_V_fu_618);

assign tmp_1_47_fu_2693_p2 = (ref_points_63_V_48_fu_370 - datamem_48_V_fu_622);

assign tmp_1_48_fu_2719_p2 = (ref_points_63_V_49_fu_374 - datamem_49_V_fu_626);

assign tmp_1_49_fu_2745_p2 = (ref_points_63_V_50_fu_378 - datamem_50_V_fu_630);

assign tmp_1_4_7_fu_1549_p2 = (ref_points_63_V_4_fu_194 - datamem_4_V_fu_446);

assign tmp_1_4_fu_1465_p2 = (datamem_1_V_fu_434 - ref_points_63_V_1_fu_182);

assign tmp_1_50_fu_2771_p2 = (ref_points_63_V_51_fu_382 - datamem_51_V_fu_634);

assign tmp_1_51_fu_2797_p2 = (ref_points_63_V_52_fu_386 - datamem_52_V_fu_638);

assign tmp_1_52_fu_2823_p2 = (ref_points_63_V_53_fu_390 - datamem_53_V_fu_642);

assign tmp_1_53_fu_2849_p2 = (ref_points_63_V_54_fu_394 - datamem_54_V_fu_646);

assign tmp_1_54_fu_2875_p2 = (ref_points_63_V_55_fu_398 - datamem_55_V_fu_650);

assign tmp_1_55_fu_2901_p2 = (ref_points_63_V_56_fu_402 - datamem_56_V_fu_654);

assign tmp_1_56_fu_2927_p2 = (ref_points_63_V_57_fu_406 - datamem_57_V_fu_658);

assign tmp_1_57_fu_2953_p2 = (ref_points_63_V_58_fu_410 - datamem_58_V_fu_662);

assign tmp_1_58_fu_2979_p2 = (ref_points_63_V_59_fu_414 - datamem_59_V_fu_666);

assign tmp_1_59_fu_3005_p2 = (ref_points_63_V_60_fu_418 - datamem_60_V_fu_670);

assign tmp_1_5_fu_1575_p2 = (ref_points_63_V_5_fu_198 - datamem_5_V_fu_450);

assign tmp_1_60_fu_3031_p2 = (ref_points_63_V_61_fu_422 - datamem_61_V_fu_674);

assign tmp_1_61_fu_3057_p2 = (ref_points_63_V_62_fu_426 - datamem_62_V_fu_678);

assign tmp_1_62_fu_3083_p2 = (ref_points_63_V_63_fu_430 - datamem_62_V_1_fu_682);

assign tmp_1_6_fu_1601_p2 = (ref_points_63_V_6_fu_202 - datamem_6_V_fu_454);

assign tmp_1_7_fu_1627_p2 = (ref_points_63_V_7_fu_206 - datamem_7_V_fu_458);

assign tmp_1_8_fu_1653_p2 = (ref_points_63_V_8_fu_210 - datamem_8_V_fu_462);

assign tmp_1_9_fu_1679_p2 = (ref_points_63_V_9_fu_214 - datamem_9_V_fu_466);

assign tmp_1_s_fu_1705_p2 = (ref_points_63_V_10_fu_218 - datamem_10_V_fu_470);

assign tmp_20_fu_1985_p2 = (datamem_21_V_fu_514 - ref_points_63_V_21_fu_262);

assign tmp_21_fu_2011_p2 = (datamem_22_V_fu_518 - ref_points_63_V_22_fu_266);

assign tmp_22_fu_2037_p2 = (datamem_23_V_fu_522 - ref_points_63_V_23_fu_270);

assign tmp_23_fu_2063_p2 = (datamem_24_V_fu_526 - ref_points_63_V_24_fu_274);

assign tmp_24_fu_2089_p2 = (datamem_25_V_fu_530 - ref_points_63_V_25_fu_278);

assign tmp_25_fu_2115_p2 = (datamem_26_V_fu_534 - ref_points_63_V_26_fu_282);

assign tmp_26_fu_2141_p2 = (datamem_27_V_fu_538 - ref_points_63_V_27_fu_286);

assign tmp_27_fu_2167_p2 = (datamem_28_V_fu_542 - ref_points_63_V_28_fu_290);

assign tmp_28_fu_2193_p2 = (datamem_29_V_fu_546 - ref_points_63_V_29_fu_294);

assign tmp_29_fu_2219_p2 = (datamem_30_V_fu_550 - ref_points_63_V_30_fu_298);

assign tmp_2_5_fu_1491_p2 = (datamem_2_V_fu_438 - ref_points_63_V_2_fu_186);

assign tmp_2_fu_1445_p2 = (ref_points_63_V_fu_178 - datain_V_dout);

assign tmp_30_fu_2245_p2 = (datamem_31_V_fu_554 - ref_points_63_V_31_fu_302);

assign tmp_31_fu_2271_p2 = (datamem_32_V_fu_558 - ref_points_63_V_32_fu_306);

assign tmp_32_fu_2297_p2 = (datamem_33_V_fu_562 - ref_points_63_V_33_fu_310);

assign tmp_33_fu_2323_p2 = (datamem_34_V_fu_566 - ref_points_63_V_34_fu_314);

assign tmp_34_fu_2349_p2 = (datamem_35_V_fu_570 - ref_points_63_V_35_fu_318);

assign tmp_35_fu_2375_p2 = (datamem_36_V_fu_574 - ref_points_63_V_36_fu_322);

assign tmp_36_fu_2401_p2 = (datamem_37_V_fu_578 - ref_points_63_V_37_fu_326);

assign tmp_37_fu_2427_p2 = (datamem_38_V_fu_582 - ref_points_63_V_38_fu_330);

assign tmp_38_fu_2453_p2 = (datamem_39_V_fu_586 - ref_points_63_V_39_fu_334);

assign tmp_39_fu_2479_p2 = (datamem_40_V_fu_590 - ref_points_63_V_40_fu_338);

assign tmp_3_6_fu_1517_p2 = (datamem_3_V_fu_442 - ref_points_63_V_3_fu_190);

assign tmp_3_fu_728_p1 = i_reg_705[5:0];

assign tmp_40_fu_2505_p2 = (datamem_41_V_fu_594 - ref_points_63_V_41_fu_342);

assign tmp_41_fu_2531_p2 = (datamem_42_V_fu_598 - ref_points_63_V_42_fu_346);

assign tmp_42_fu_2557_p2 = (datamem_43_V_fu_602 - ref_points_63_V_43_fu_350);

assign tmp_43_fu_2583_p2 = (datamem_44_V_fu_606 - ref_points_63_V_44_fu_354);

assign tmp_44_fu_2609_p2 = (datamem_45_V_fu_610 - ref_points_63_V_45_fu_358);

assign tmp_45_fu_2635_p2 = (datamem_46_V_fu_614 - ref_points_63_V_46_fu_362);

assign tmp_46_fu_2661_p2 = (datamem_47_V_fu_618 - ref_points_63_V_47_fu_366);

assign tmp_47_fu_2687_p2 = (datamem_48_V_fu_622 - ref_points_63_V_48_fu_370);

assign tmp_48_fu_2713_p2 = (datamem_49_V_fu_626 - ref_points_63_V_49_fu_374);

assign tmp_49_fu_2739_p2 = (datamem_50_V_fu_630 - ref_points_63_V_50_fu_378);

assign tmp_4_fu_1543_p2 = (datamem_4_V_fu_446 - ref_points_63_V_4_fu_194);

assign tmp_50_fu_2765_p2 = (datamem_51_V_fu_634 - ref_points_63_V_51_fu_382);

assign tmp_51_fu_2791_p2 = (datamem_52_V_fu_638 - ref_points_63_V_52_fu_386);

assign tmp_52_fu_2817_p2 = (datamem_53_V_fu_642 - ref_points_63_V_53_fu_390);

assign tmp_53_fu_2843_p2 = (datamem_54_V_fu_646 - ref_points_63_V_54_fu_394);

assign tmp_54_fu_2869_p2 = (datamem_55_V_fu_650 - ref_points_63_V_55_fu_398);

assign tmp_55_fu_2895_p2 = (datamem_56_V_fu_654 - ref_points_63_V_56_fu_402);

assign tmp_56_fu_2921_p2 = (datamem_57_V_fu_658 - ref_points_63_V_57_fu_406);

assign tmp_57_fu_2947_p2 = (datamem_58_V_fu_662 - ref_points_63_V_58_fu_410);

assign tmp_58_fu_2973_p2 = (datamem_59_V_fu_666 - ref_points_63_V_59_fu_414);

assign tmp_59_fu_2999_p2 = (datamem_60_V_fu_670 - ref_points_63_V_60_fu_418);

assign tmp_5_fu_1569_p2 = (datamem_5_V_fu_450 - ref_points_63_V_5_fu_198);

assign tmp_60_fu_3025_p2 = (datamem_61_V_fu_674 - ref_points_63_V_61_fu_422);

assign tmp_61_fu_3051_p2 = (datamem_62_V_fu_678 - ref_points_63_V_62_fu_426);

assign tmp_62_fu_3077_p2 = (datamem_62_V_1_fu_682 - ref_points_63_V_63_fu_430);

assign tmp_6_10_cast_fu_3141_p1 = sumtree_11_V_fu_1737_p3;

assign tmp_6_11_cast_fu_3145_p1 = sumtree_12_V_fu_1763_p3;

assign tmp_6_12_cast_fu_3149_p1 = sumtree_13_V_fu_1789_p3;

assign tmp_6_13_cast_fu_3153_p1 = sumtree_14_V_fu_1815_p3;

assign tmp_6_14_cast_fu_3157_p1 = sumtree_15_V_fu_1841_p3;

assign tmp_6_15_cast_fu_3161_p1 = sumtree_16_V_fu_1867_p3;

assign tmp_6_16_cast_fu_3165_p1 = sumtree_17_V_fu_1893_p3;

assign tmp_6_17_cast_fu_3169_p1 = sumtree_18_V_fu_1919_p3;

assign tmp_6_18_cast_fu_3173_p1 = sumtree_19_V_fu_1945_p3;

assign tmp_6_19_cast_fu_3177_p1 = sumtree_20_V_fu_1971_p3;

assign tmp_6_1_cast_fu_3101_p1 = sumtree_1_V_fu_1477_p3;

assign tmp_6_20_cast_fu_3181_p1 = sumtree_21_V_fu_1997_p3;

assign tmp_6_21_cast_fu_3185_p1 = sumtree_22_V_fu_2023_p3;

assign tmp_6_22_cast_fu_3189_p1 = sumtree_23_V_fu_2049_p3;

assign tmp_6_23_cast_fu_3193_p1 = sumtree_24_V_fu_2075_p3;

assign tmp_6_24_cast_fu_3197_p1 = sumtree_25_V_fu_2101_p3;

assign tmp_6_25_cast_fu_3201_p1 = sumtree_26_V_fu_2127_p3;

assign tmp_6_26_cast_fu_3205_p1 = sumtree_27_V_fu_2153_p3;

assign tmp_6_27_cast_fu_3209_p1 = sumtree_28_V_fu_2179_p3;

assign tmp_6_28_cast_fu_3213_p1 = sumtree_29_V_fu_2205_p3;

assign tmp_6_29_cast_fu_3217_p1 = sumtree_30_V_fu_2231_p3;

assign tmp_6_2_cast_fu_3105_p1 = sumtree_2_V_fu_1503_p3;

assign tmp_6_30_cast_fu_3221_p1 = sumtree_31_V_fu_2257_p3;

assign tmp_6_31_cast_fu_3225_p1 = sumtree_32_V_fu_2283_p3;

assign tmp_6_32_cast_fu_3229_p1 = sumtree_33_V_fu_2309_p3;

assign tmp_6_33_cast_fu_3233_p1 = sumtree_34_V_fu_2335_p3;

assign tmp_6_34_cast_fu_3237_p1 = sumtree_35_V_fu_2361_p3;

assign tmp_6_35_cast_fu_3241_p1 = sumtree_36_V_fu_2387_p3;

assign tmp_6_36_cast_fu_3245_p1 = sumtree_37_V_fu_2413_p3;

assign tmp_6_37_cast_fu_3249_p1 = sumtree_38_V_fu_2439_p3;

assign tmp_6_38_cast_fu_3253_p1 = sumtree_39_V_fu_2465_p3;

assign tmp_6_39_cast_fu_3257_p1 = sumtree_40_V_fu_2491_p3;

assign tmp_6_3_cast_fu_3109_p1 = sumtree_3_V_fu_1529_p3;

assign tmp_6_40_cast_fu_3261_p1 = sumtree_41_V_fu_2517_p3;

assign tmp_6_41_cast_fu_3265_p1 = sumtree_42_V_fu_2543_p3;

assign tmp_6_42_cast_fu_3269_p1 = sumtree_43_V_fu_2569_p3;

assign tmp_6_43_cast_fu_3273_p1 = sumtree_44_V_fu_2595_p3;

assign tmp_6_44_cast_fu_3277_p1 = sumtree_45_V_fu_2621_p3;

assign tmp_6_45_cast_fu_3281_p1 = sumtree_46_V_fu_2647_p3;

assign tmp_6_46_cast_fu_3285_p1 = sumtree_47_V_fu_2673_p3;

assign tmp_6_47_cast_fu_3289_p1 = sumtree_48_V_fu_2699_p3;

assign tmp_6_48_cast_fu_3293_p1 = sumtree_49_V_fu_2725_p3;

assign tmp_6_49_cast_fu_3297_p1 = sumtree_50_V_fu_2751_p3;

assign tmp_6_4_cast_fu_3113_p1 = sumtree_4_V_fu_1555_p3;

assign tmp_6_50_cast_fu_3301_p1 = sumtree_51_V_fu_2777_p3;

assign tmp_6_51_cast_fu_3305_p1 = sumtree_52_V_fu_2803_p3;

assign tmp_6_52_cast_fu_3309_p1 = sumtree_53_V_fu_2829_p3;

assign tmp_6_53_cast_fu_3313_p1 = sumtree_54_V_fu_2855_p3;

assign tmp_6_54_cast_fu_3317_p1 = sumtree_55_V_fu_2881_p3;

assign tmp_6_55_cast_fu_3321_p1 = sumtree_56_V_fu_2907_p3;

assign tmp_6_56_cast_fu_3325_p1 = sumtree_57_V_fu_2933_p3;

assign tmp_6_57_cast_fu_3329_p1 = sumtree_58_V_fu_2959_p3;

assign tmp_6_58_cast_fu_3333_p1 = sumtree_59_V_fu_2985_p3;

assign tmp_6_59_cast_fu_3337_p1 = sumtree_60_V_fu_3011_p3;

assign tmp_6_5_cast_fu_3117_p1 = sumtree_5_V_fu_1581_p3;

assign tmp_6_60_cast_fu_3341_p1 = sumtree_61_V_fu_3037_p3;

assign tmp_6_61_cast_fu_3345_p1 = sumtree_62_V_fu_3063_p3;

assign tmp_6_62_cast_fu_3349_p1 = sumtree_63_V_fu_3089_p3;

assign tmp_6_6_cast_fu_3121_p1 = sumtree_6_V_fu_1607_p3;

assign tmp_6_7_cast_fu_3125_p1 = sumtree_7_V_fu_1633_p3;

assign tmp_6_8_cast_fu_3129_p1 = sumtree_8_V_fu_1659_p3;

assign tmp_6_9_cast_fu_3133_p1 = sumtree_9_V_fu_1685_p3;

assign tmp_6_cast_13_fu_3137_p1 = sumtree_10_V_fu_1711_p3;

assign tmp_6_cast_fu_3097_p1 = sumtree_0_V_fu_1451_p3;

assign tmp_6_fu_1595_p2 = (datamem_6_V_fu_454 - ref_points_63_V_6_fu_202);

assign tmp_7_fu_1621_p2 = (datamem_7_V_fu_458 - ref_points_63_V_7_fu_206);

assign tmp_8_fu_1647_p2 = (datamem_8_V_fu_462 - ref_points_63_V_8_fu_210);

assign tmp_9_10_12_fu_1719_p2 = ((datamem_11_V_fu_474 > ref_points_63_V_11_fu_222) ? 1'b1 : 1'b0);

assign tmp_9_10_fu_1673_p2 = (datamem_9_V_fu_466 - ref_points_63_V_9_fu_214);

assign tmp_9_11_fu_1745_p2 = ((datamem_12_V_fu_478 > ref_points_63_V_12_fu_226) ? 1'b1 : 1'b0);

assign tmp_9_12_fu_1771_p2 = ((datamem_13_V_fu_482 > ref_points_63_V_13_fu_230) ? 1'b1 : 1'b0);

assign tmp_9_13_fu_1797_p2 = ((datamem_14_V_fu_486 > ref_points_63_V_14_fu_234) ? 1'b1 : 1'b0);

assign tmp_9_14_fu_1823_p2 = ((datamem_15_V_fu_490 > ref_points_63_V_15_fu_238) ? 1'b1 : 1'b0);

assign tmp_9_15_fu_1849_p2 = ((datamem_16_V_fu_494 > ref_points_63_V_16_fu_242) ? 1'b1 : 1'b0);

assign tmp_9_16_fu_1875_p2 = ((datamem_17_V_fu_498 > ref_points_63_V_17_fu_246) ? 1'b1 : 1'b0);

assign tmp_9_17_fu_1901_p2 = ((datamem_18_V_fu_502 > ref_points_63_V_18_fu_250) ? 1'b1 : 1'b0);

assign tmp_9_18_fu_1927_p2 = ((datamem_19_V_fu_506 > ref_points_63_V_19_fu_254) ? 1'b1 : 1'b0);

assign tmp_9_19_fu_1953_p2 = ((datamem_20_V_fu_510 > ref_points_63_V_20_fu_258) ? 1'b1 : 1'b0);

assign tmp_9_1_fu_1459_p2 = ((datamem_1_V_fu_434 > ref_points_63_V_1_fu_182) ? 1'b1 : 1'b0);

assign tmp_9_20_fu_1979_p2 = ((datamem_21_V_fu_514 > ref_points_63_V_21_fu_262) ? 1'b1 : 1'b0);

assign tmp_9_21_fu_2005_p2 = ((datamem_22_V_fu_518 > ref_points_63_V_22_fu_266) ? 1'b1 : 1'b0);

assign tmp_9_22_fu_2031_p2 = ((datamem_23_V_fu_522 > ref_points_63_V_23_fu_270) ? 1'b1 : 1'b0);

assign tmp_9_23_fu_2057_p2 = ((datamem_24_V_fu_526 > ref_points_63_V_24_fu_274) ? 1'b1 : 1'b0);

assign tmp_9_24_fu_2083_p2 = ((datamem_25_V_fu_530 > ref_points_63_V_25_fu_278) ? 1'b1 : 1'b0);

assign tmp_9_25_fu_2109_p2 = ((datamem_26_V_fu_534 > ref_points_63_V_26_fu_282) ? 1'b1 : 1'b0);

assign tmp_9_26_fu_2135_p2 = ((datamem_27_V_fu_538 > ref_points_63_V_27_fu_286) ? 1'b1 : 1'b0);

assign tmp_9_27_fu_2161_p2 = ((datamem_28_V_fu_542 > ref_points_63_V_28_fu_290) ? 1'b1 : 1'b0);

assign tmp_9_28_fu_2187_p2 = ((datamem_29_V_fu_546 > ref_points_63_V_29_fu_294) ? 1'b1 : 1'b0);

assign tmp_9_29_fu_2213_p2 = ((datamem_30_V_fu_550 > ref_points_63_V_30_fu_298) ? 1'b1 : 1'b0);

assign tmp_9_2_fu_1485_p2 = ((datamem_2_V_fu_438 > ref_points_63_V_2_fu_186) ? 1'b1 : 1'b0);

assign tmp_9_30_fu_2239_p2 = ((datamem_31_V_fu_554 > ref_points_63_V_31_fu_302) ? 1'b1 : 1'b0);

assign tmp_9_31_fu_2265_p2 = ((datamem_32_V_fu_558 > ref_points_63_V_32_fu_306) ? 1'b1 : 1'b0);

assign tmp_9_32_fu_2291_p2 = ((datamem_33_V_fu_562 > ref_points_63_V_33_fu_310) ? 1'b1 : 1'b0);

assign tmp_9_33_fu_2317_p2 = ((datamem_34_V_fu_566 > ref_points_63_V_34_fu_314) ? 1'b1 : 1'b0);

assign tmp_9_34_fu_2343_p2 = ((datamem_35_V_fu_570 > ref_points_63_V_35_fu_318) ? 1'b1 : 1'b0);

assign tmp_9_35_fu_2369_p2 = ((datamem_36_V_fu_574 > ref_points_63_V_36_fu_322) ? 1'b1 : 1'b0);

assign tmp_9_36_fu_2395_p2 = ((datamem_37_V_fu_578 > ref_points_63_V_37_fu_326) ? 1'b1 : 1'b0);

assign tmp_9_37_fu_2421_p2 = ((datamem_38_V_fu_582 > ref_points_63_V_38_fu_330) ? 1'b1 : 1'b0);

assign tmp_9_38_fu_2447_p2 = ((datamem_39_V_fu_586 > ref_points_63_V_39_fu_334) ? 1'b1 : 1'b0);

assign tmp_9_39_fu_2473_p2 = ((datamem_40_V_fu_590 > ref_points_63_V_40_fu_338) ? 1'b1 : 1'b0);

assign tmp_9_3_fu_1511_p2 = ((datamem_3_V_fu_442 > ref_points_63_V_3_fu_190) ? 1'b1 : 1'b0);

assign tmp_9_40_fu_2499_p2 = ((datamem_41_V_fu_594 > ref_points_63_V_41_fu_342) ? 1'b1 : 1'b0);

assign tmp_9_41_fu_2525_p2 = ((datamem_42_V_fu_598 > ref_points_63_V_42_fu_346) ? 1'b1 : 1'b0);

assign tmp_9_42_fu_2551_p2 = ((datamem_43_V_fu_602 > ref_points_63_V_43_fu_350) ? 1'b1 : 1'b0);

assign tmp_9_43_fu_2577_p2 = ((datamem_44_V_fu_606 > ref_points_63_V_44_fu_354) ? 1'b1 : 1'b0);

assign tmp_9_44_fu_2603_p2 = ((datamem_45_V_fu_610 > ref_points_63_V_45_fu_358) ? 1'b1 : 1'b0);

assign tmp_9_45_fu_2629_p2 = ((datamem_46_V_fu_614 > ref_points_63_V_46_fu_362) ? 1'b1 : 1'b0);

assign tmp_9_46_fu_2655_p2 = ((datamem_47_V_fu_618 > ref_points_63_V_47_fu_366) ? 1'b1 : 1'b0);

assign tmp_9_47_fu_2681_p2 = ((datamem_48_V_fu_622 > ref_points_63_V_48_fu_370) ? 1'b1 : 1'b0);

assign tmp_9_48_fu_2707_p2 = ((datamem_49_V_fu_626 > ref_points_63_V_49_fu_374) ? 1'b1 : 1'b0);

assign tmp_9_49_fu_2733_p2 = ((datamem_50_V_fu_630 > ref_points_63_V_50_fu_378) ? 1'b1 : 1'b0);

assign tmp_9_4_fu_1537_p2 = ((datamem_4_V_fu_446 > ref_points_63_V_4_fu_194) ? 1'b1 : 1'b0);

assign tmp_9_50_fu_2759_p2 = ((datamem_51_V_fu_634 > ref_points_63_V_51_fu_382) ? 1'b1 : 1'b0);

assign tmp_9_51_fu_2785_p2 = ((datamem_52_V_fu_638 > ref_points_63_V_52_fu_386) ? 1'b1 : 1'b0);

assign tmp_9_52_fu_2811_p2 = ((datamem_53_V_fu_642 > ref_points_63_V_53_fu_390) ? 1'b1 : 1'b0);

assign tmp_9_53_fu_2837_p2 = ((datamem_54_V_fu_646 > ref_points_63_V_54_fu_394) ? 1'b1 : 1'b0);

assign tmp_9_54_fu_2863_p2 = ((datamem_55_V_fu_650 > ref_points_63_V_55_fu_398) ? 1'b1 : 1'b0);

assign tmp_9_55_fu_2889_p2 = ((datamem_56_V_fu_654 > ref_points_63_V_56_fu_402) ? 1'b1 : 1'b0);

assign tmp_9_56_fu_2915_p2 = ((datamem_57_V_fu_658 > ref_points_63_V_57_fu_406) ? 1'b1 : 1'b0);

assign tmp_9_57_fu_2941_p2 = ((datamem_58_V_fu_662 > ref_points_63_V_58_fu_410) ? 1'b1 : 1'b0);

assign tmp_9_58_fu_2967_p2 = ((datamem_59_V_fu_666 > ref_points_63_V_59_fu_414) ? 1'b1 : 1'b0);

assign tmp_9_59_fu_2993_p2 = ((datamem_60_V_fu_670 > ref_points_63_V_60_fu_418) ? 1'b1 : 1'b0);

assign tmp_9_5_fu_1563_p2 = ((datamem_5_V_fu_450 > ref_points_63_V_5_fu_198) ? 1'b1 : 1'b0);

assign tmp_9_60_fu_3019_p2 = ((datamem_61_V_fu_674 > ref_points_63_V_61_fu_422) ? 1'b1 : 1'b0);

assign tmp_9_61_fu_3045_p2 = ((datamem_62_V_fu_678 > ref_points_63_V_62_fu_426) ? 1'b1 : 1'b0);

assign tmp_9_62_fu_3071_p2 = ((datamem_62_V_1_fu_682 > ref_points_63_V_63_fu_430) ? 1'b1 : 1'b0);

assign tmp_9_6_fu_1589_p2 = ((datamem_6_V_fu_454 > ref_points_63_V_6_fu_202) ? 1'b1 : 1'b0);

assign tmp_9_7_fu_1615_p2 = ((datamem_7_V_fu_458 > ref_points_63_V_7_fu_206) ? 1'b1 : 1'b0);

assign tmp_9_8_fu_1641_p2 = ((datamem_8_V_fu_462 > ref_points_63_V_8_fu_210) ? 1'b1 : 1'b0);

assign tmp_9_9_fu_1667_p2 = ((datamem_9_V_fu_466 > ref_points_63_V_9_fu_214) ? 1'b1 : 1'b0);

assign tmp_9_fu_1433_p2 = ((datain_V_dout > ref_points_63_V_fu_178) ? 1'b1 : 1'b0);

assign tmp_9_s_fu_1693_p2 = ((datamem_10_V_fu_470 > ref_points_63_V_10_fu_218) ? 1'b1 : 1'b0);

assign tmp_cast_fu_3659_p1 = tmp_fu_3653_p2;

assign tmp_fu_3653_p2 = (tmp16_cast_fu_3649_p1 + tmp1_cast_fu_3499_p1);

assign tmp_s_11_fu_1699_p2 = (datamem_10_V_fu_470 - ref_points_63_V_10_fu_218);

assign tmp_s_fu_1439_p2 = (datain_V_dout - ref_points_63_V_fu_178);

assign totalsum_V_s_fu_3973_p2 = (tmp31_cast_fu_3969_p1 + tmp_cast_fu_3659_p1);

endmodule //sad
